// The template library — studio-grade. Each template lives in its own module:
// page artifacts under ./pages/<id>.ts, slide decks under ./decks/<id>.ts. Every
// module exports a `Template` with a self-contained, fully-built sample.
//
// GENERATED by scripts/build-catalog.mjs — do not hand-edit the lists below.
// To add a template: drop a module in ./pages/ or ./decks/, add its id to ORDER
// in the script, then run `node scripts/build-catalog.mjs`.
import { boldFounder } from './decks/bold-founder'
import { darkTech } from './decks/dark-tech'
import { dataDashboard } from './decks/data-dashboard'
import { editorial } from './decks/editorial'
import { financePro } from './decks/finance-pro'
import { game2048 } from './pages/2048'
import { agency } from './pages/agency'
import { analyticsDashboard } from './pages/analytics-dashboard'
import { article } from './pages/article'
import { blog } from './pages/blog'
import { breakout } from './pages/breakout'
import { businessHome } from './pages/business-home'
import { caseStudy } from './pages/case-study'
import { changelog } from './pages/changelog'
import { comingSoon } from './pages/coming-soon'
import { course } from './pages/course'
import { cryptoDashboard } from './pages/crypto-dashboard'
import { docs } from './pages/docs'
import { eventConf } from './pages/event-conf'
import { financialReport } from './pages/financial-report'
import { fitnessStats } from './pages/fitness-stats'
import { landingPage } from './pages/landing-page'
import { linkInBio } from './pages/link-in-bio'
import { memory } from './pages/memory'
import { moldableBird } from './pages/moldable-bird'
import { particleToy } from './pages/particle-toy'
import { personalSite } from './pages/personal-site'
import { petPage } from './pages/pet-page'
import { pitchOnepager } from './pages/pitch-onepager'
import { portfolio } from './pages/portfolio'
import { pricing } from './pages/pricing'
import { productSpec } from './pages/product-spec'
import { quiz } from './pages/quiz'
import { recipe } from './pages/recipe'
import { restaurant } from './pages/restaurant'
import { resume } from './pages/resume'
import { snake } from './pages/snake'
import { threeDOrb } from './pages/three-d-orb'
import { threeGlobe } from './pages/three-globe'
import { threeTerrain } from './pages/three-terrain'
import { travelJournal } from './pages/travel-journal'
import { weather } from './pages/weather'
import { wedding } from './pages/wedding'
import type { Template } from './types'

export const TEMPLATES: Template[] = [
  resume,
  personalSite,
  portfolio,
  linkInBio,
  petPage,
  travelJournal,
  wedding,
  landingPage,
  pitchOnepager,
  agency,
  pricing,
  comingSoon,
  caseStudy,
  businessHome,
  restaurant,
  course,
  eventConf,
  blog,
  article,
  recipe,
  docs,
  changelog,
  productSpec,
  analyticsDashboard,
  financialReport,
  cryptoDashboard,
  fitnessStats,
  weather,
  moldableBird,
  snake,
  breakout,
  game2048,
  memory,
  quiz,
  threeDOrb,
  threeGlobe,
  threeTerrain,
  particleToy,
  boldFounder,
  editorial,
  darkTech,
  financePro,
  dataDashboard,
]
