// The seeded starter deck. Built from the Bold Founder library template so it
// uses the shared component vocabulary — a live example of the style system.
import { getTemplate, templateTheme } from './templates'
import type { Deck, Slide } from './types'

function slide(s: Slide): Slide {
  return s
}

export function createWelcomeDeck(id: string, now: string): Deck {
  const template = getTemplate('bold-founder')
  const theme = template
    ? templateTheme(template)
    : { fontLinks: [], css: '', stageBg: undefined }

  return {
    id,
    title: 'Welcome to Slides',
    subtitle: 'Generate beautiful decks from chat',
    density: 'low',
    templateId: template?.id,
    theme,
    slides: [
      slide({
        id: 'welcome',
        name: 'Title',
        slideClass: 'title-slide',
        transition: 'zoom',
        notes:
          'Welcome. This deck was generated by the Slides app. Press → to continue.',
        bodyHtml: `<div class="pad center">
  <div class="kicker reveal">Moldable · Slides</div>
  <h1 class="title reveal">Decks that feel <span class="grad-text">designed.</span></h1>
  <p class="lead reveal">Describe what you want in chat. Get a beautiful, animated, publishable presentation.</p>
</div>`,
      }),
      slide({
        id: 'how',
        name: 'How it works',
        transition: 'slide',
        notes:
          'Everything is driven from chat via RPC. The UI is for viewing, presenting, and publishing.',
        bodyHtml: `<div class="pad">
  <h2 class="headline reveal">How it works</h2>
  <ul class="bullets reveal">
    <li class="bullet"><span><b>Pick a style.</b> Choose from the library — clean, bold, finance, classroom, and more.</span></li>
    <li class="bullet"><span><b>Chat authors it.</b> Ask the assistant to add, edit, reorder, or restyle slides.</span></li>
    <li class="bullet"><span><b>Publish to a link.</b> One click shares a static, animated deck that works anywhere.</span></li>
  </ul>
</div>`,
      }),
      slide({
        id: 'cta',
        name: 'Get started',
        transition: 'fade',
        notes: 'Prompt them to start. Suggest a topic.',
        bodyHtml: `<div class="pad center">
  <div class="kicker reveal">Your turn</div>
  <h2 class="headline reveal">Try: <span class="grad-text">"Make a 6-slide pitch for…"</span></h2>
  <p class="lead reveal">Then hit Present, or Publish to get a shareable link.</p>
</div>`,
      }),
    ],
    published: null,
    publishPending: false,
    publishError: null,
    createdAt: now,
    updatedAt: now,
  }
}
