export const CATEGORY_PROMPTS: Record<string, string[]> = {
  'cells-microbes': [
    'A tardigrade specimen',
    'A bacteriophage virus particle',
    'A malaria parasite inside a red blood cell',
    'A radiolarian silica skeleton',
    'A white blood cell with a lobed nucleus',
    'A hydra polyp',
    'A coronavirus particle',
    'A neuron cell body with dendrites',
    'A sperm cell',
    'A plant cell cross-section',
    'A pollen grain with spiked armor',
    'A paramecium specimen',
    'A mitochondrion cutaway',
    'A red blood cell biconcave disc',
    'A slime mold spore capsule',
    'A bacterium dividing by binary fission',
    'A frog egg cell',
    'A Golgi apparatus stack',
    'A macrophage cell',
    'A foraminifera shell',
    'An amoeba with pseudopods',
    'A pine pollen grain with air sacs',
    'A spiral-shaped spirochete bacterium',
    'A cell nucleus with nucleolus',
    'A DNA nucleosome bead',
    'An HIV virion cutaway',
    'A rod-shaped bacterium with flagella',
    'A planarian flatworm head',
    'A ragweed pollen grain',
    'An aspergillus conidial head',
    'A lysosome vesicle cluster',
    'A chromosome X shape',
    'An influenza virus particle',
    'An animal cell cross-section',
    'A fungal hypha tip',
    'A cilium cross-section',
    'A microtubule bundle',
    'A human egg cell',
    'A staphylococcus cell cluster',
    'A cell membrane lipid bilayer',
    'A fern spore',
    'A centrosome pair',
    'A herpesvirus capsid',
    'A bacterial biofilm cross-section',
    'A euglena with a flagellum',
    'A penicillium conidiophore',
    'A flagellum cross-section',
    'A white blood cell engulfing a bacterium',
    'A cyanobacteria filament',
    'A nematode worm',
    'A volvox daughter colony',
    'A yeast cell budding',
    'A bread mold sporangium',
    'A mushroom spore print cluster',
    'A water bear claw',
    'A chloroplast thylakoid stack',
  ],
  'human-body': [
    'A human heart anatomical model',
    'A human eye cutaway',
    'A human embryo at 12 weeks',
    'A human skull',
    'A blood clot mesh',
    'A cochlea spiral',
    'A cancer cell cluster',
    'A knee joint cutaway',
    'A tooth cross-section with a cavity',
    'A lung alveolus cluster',
    'A placenta villus cross-section',
    'A myelinated nerve fiber',
    'A skin cross-section',
    'A human jaw with teeth',
    'A kidney glomerulus',
    'A fingerprint ridge cross-section',
    'A muscle fiber bundle',
    'A lymph node cross-section',
    'A heart valve cross-section',
    'A liver lobule',
    'A bronchial airway with mucus',
    'A fetal hand at 12 weeks',
    'A retina layer cross-section',
    'A spinal vertebra',
    'A clogged artery cross-section',
    'A stomach lining fold',
    'A hair follicle',
    'A hippocampus model',
    'A shoulder joint cutaway',
    'A kidney nephron',
    'A tongue papilla',
    'A thyroid gland follicle',
    'A tendon fiber bundle',
    'An ovarian follicle',
    'A hand skeleton',
    'A spleen white pulp nodule',
    'A molar tooth root',
    'A pancreas islet',
    'A red blood cell in a capillary',
    'A spinal cord cross-section',
    'A healing scab cross-section',
    'A prostate gland cross-section',
    'A human brain hemisphere',
    'A colon crypt',
    'A sweat gland coil',
    'A hip joint cutaway',
    'A coronary artery cross-section',
    'A diseased lung alveolus cluster',
    'A small intestine villus',
    'A bone marrow cross-section',
    'A human embryo at 8 weeks',
    'A testis seminiferous tubule',
    'A plaque-covered artery',
    'An inner ear balance organ',
    'A foot arch skeleton',
    'A breast milk droplet structure',
  ],
  animals: [
    'A Tyrannosaurus rex skull',
    'A great white shark jaw',
    'A monarch butterfly chrysalis',
    'An octopus arm with suction cups',
    'A jumping spider face',
    'A rattlesnake rattle',
    'A blue-ringed octopus',
    'A gecko foot pad',
    'A rhinoceros beetle horn',
    'A wolf skull',
    'A scorpion stinger',
    'A bat wing skeleton',
    'A vampire squid body',
    'A hummingbird skull',
    'A pangolin scale',
    'A frog skeleton',
    'A dragonfly head',
    'A nautilus shell cutaway',
    'A velociraptor claw',
    'A great white shark tooth',
    'A manta ray gill plate',
    'A tarantula fang',
    'A snake fang',
    'A lobster claw',
    'A bird wing anatomy model',
    'A squid beak',
    'A butterfly wing scale patch',
    'A cat skull',
    'A shark skin denticle',
    'A turtle skull',
    'A honeybee stinger',
    'A sea urchin test',
    'A bear claw',
    'A dolphin skull',
    'A crab claw',
    'A snail shell cutaway',
    'A beetle elytra wing case',
    'A penguin flipper bone',
    'A whale vertebra',
    'A flea body',
    'A starfish arm cross-section',
    'A shrimp with a transparent shell',
    'A caterpillar head capsule',
    'An owl skull',
    'A spider spinneret',
    'A sea anemone polyp',
    'A ladybug shell',
    'A mosquito proboscis',
    'An eagle talon',
    'An elephant molar',
    'A deer antler cross-section',
    'A dragonfly wing section',
    'A frog egg',
    'A horseshoe crab tail spine',
    'A triceratops horn core',
    'A trilobite body fossil',
  ],
  'plants-fungi': [
    'A Venus flytrap leaf',
    'A pitcher plant trap',
    'A mushroom gill section',
    'A lotus seed pod',
    'A sundew leaf with sticky hairs',
    'A cactus spine cluster',
    'A morel mushroom cap',
    'A pine cone scale',
    'A flower ovary cross-section',
    'A fern fiddlehead',
    'A mycorrhizal root tip',
    'A lichen thallus cross-section',
    'A bean seed cross-section',
    'A bracket fungus pore surface',
    'A stomata pore on a leaf',
    'A moss capsule',
    'An orchid flower column',
    'A root nodule with bacteria',
    'A leaf cross-section',
    'A plant root tip with root hairs',
    'A puffball mushroom cutaway',
    'A dandelion seed',
    'A chloroplast cutaway',
    'A plant xylem vessel',
    'A truffle cross-section',
    'A maple seed samara',
    'A succulent leaf cross-section',
    'A fern spore capsule',
    'A mushroom cap cross-section',
    'A bamboo node cross-section',
    'A lily anther with pollen',
    'A fungal mycelium strand bundle',
    'An acorn cross-section',
    'A seaweed air bladder',
    'A chanterelle mushroom',
    'A cork cell cluster',
    'A rose hip cross-section',
    'A liverwort gemma cup',
    'A sunflower seed',
    'A phloem sieve tube',
    'A kelp gas bladder',
    'A red algae blade',
    'A grass blade cross-section',
    'A potato eye sprout',
    'A seed germinating',
    'A pine seed with wing',
    'A mushroom spore ornament',
    'A corn root hair cluster',
    'An aloe leaf cross-section',
    'A pollen tube entering an ovule',
    'A cocoa flower bud',
    'A carnivorous bladderwort trap',
    'A ginkgo seed',
    'A rafflesia flower bud',
    'A horsetail strobilus',
    'A coffee plant berry pit',
  ],
  'ecosystems-places': [
    'A Galapagos giant tortoise',
    'A Komodo dragon skull',
    'A poison dart frog',
    'A marine iguana',
    'A leafcutter ant',
    'A blue-footed booby foot',
    'A platypus bill',
    'A ring-tailed lemur',
    'A giant clam shell',
    'A sea turtle hatchling',
    'A beaver lodge cutaway',
    'A lionfish fin',
    'A kakapo beak',
    'A coral reef cleaner shrimp',
    'A polar bear paw',
    'A termite mound cutaway',
    'A mangrove propagule',
    'An emerald ash borer beetle',
    'A Darwin finch beak',
    'A Madagascar hissing cockroach',
    'A cane toad skull',
    'A tide pool anemone',
    'A clownfish body',
    'A sea otter skull',
    'A Hawaiian honeycreeper beak',
    'A kangaroo foot',
    'A desert cactus flower',
    'A salmon jaw',
    'A camel foot pad',
    'A freshwater mussel shell',
    'A rainforest bromeliad',
    'A dragonfly nymph mask',
    'A kiwi bird beak',
    'A bleached coral branch',
    'A mangrove crab claw',
    'A baobab fruit',
    'An invasive zebra mussel',
    'A freshwater sponge',
    'A seagrass rhizome',
    'A cicada shell',
    'A prairie grass seed',
    'A salmon egg',
    'A penguin egg',
    'A barnacle cluster',
    'A bison horn core',
    'A strangler fig seedling',
    'A locust body',
    'A freshwater snail shell',
    'A forest mycorrhiza root',
    'A mangrove seedling root',
    'A coral rubble fragment',
    'A desert tortoise shell',
    'A krill feeding basket',
    'A sponge reef glass sponge',
    'A rainforest orchid root',
    'A kelp forest sea urchin',
  ],
  'water-worlds': [
    'A deep-sea anglerfish',
    'A six-sided snowflake crystal',
    'A comb jelly body',
    "A Portuguese man o' war float",
    'A hydrothermal vent tube worm plume',
    'A water strider leg',
    'A frog egg cluster',
    'A sea dragon larva',
    'A shark gill raker',
    'A sand dollar test',
    'A caddisfly larva case',
    'An ice crystal dendrite',
    'A whale baleen plate',
    'A vampire squid eye',
    'A crab zoea larva',
    'A sea butterfly shell',
    'A jellyfish stinging cell',
    'A water droplet with pollen',
    'A manta ray gill filter',
    'A brine shrimp egg',
    'A glacier ice bubble',
    'A mayfly nymph',
    'A tadpole body',
    'A fish gill arch',
    'A barnacle shell',
    'A limpet shell',
    'A shrimp larva',
    'A penguin feather',
    'A seal whisker',
    'A geyserite mineral sample',
    'A stalactite formed by dripping water',
    'A mineral scale from hard water',
    'A water filter membrane',
    'An activated carbon granule',
    'A chlorine tablet dissolving',
    'A cloud droplet around dust',
    'A river pebble',
    'A coral sand grain',
    'A beach glass pebble',
    'An oil droplet in water',
    'A hoarfrost crystal',
    'A sea ice brine channel',
    'A krill specimen',
    'A pond skater insect',
    'A diving beetle larva',
    'A dragonfly nymph head',
    'A planktonic crab larva',
    'A green algae cell',
    'A red tide dinoflagellate',
    'A sea urchin spine',
    'A starfish tube foot',
    'A soap bubble film',
    'A raindrop splash crown',
    'A microplastic bead',
    'A hagfish slime thread',
    'A narwhal tusk cross-section',
  ],
  'food-materials': [
    'A house dust mite',
    'A smartphone pixel subgrid',
    'A honeycomb wax cell',
    'A popping corn kernel cutaway',
    'An eggshell cross-section',
    'A chocolate crystal bloom',
    'A wool fiber scale pattern',
    'A coffee bean cross-section',
    'A soap micelle',
    'A cotton fiber bundle',
    'A cheese curd cross-section',
    'A black peppercorn',
    'A plastic pellet',
    'A fish scale',
    'A sourdough bubble structure',
    'A cinnamon bark curl',
    'A ballpoint ink droplet',
    'A strawberry seed pit',
    'A cocoa bean cross-section',
    'A vanilla bean cross-section',
    'A yogurt bacterium',
    'A potato starch granule',
    'A silk fiber strand',
    'A concrete pore cross-section',
    'A steel wool fiber',
    'A bread yeast cell',
    'A rice grain cross-section',
    'A blueberry skin cross-section',
    'A pencil graphite core',
    'A glass fiber strand',
    'A garlic clove cross-section',
    'A laundry detergent granule',
    'A paper fiber mat',
    'A walnut shell',
    'A tapioca pearl cross-section',
    'An onion cell layer',
    'A rubber crumb',
    'A foam cell cross-section',
    'A copper wire cross-section',
    'A shrimp shell segment',
    'A sesame seed',
    'A chia seed in water',
    'A pea seed cross-section',
    'A carrot root cross-section',
    'A ceramic shard cross-section',
    'A cardboard corrugation cross-section',
    'A pasta noodle cross-section',
    'A wheat kernel cross-section',
    'A dust ball fiber cluster',
    'A broccoli floret bud',
    'An aluminum foil wrinkle',
    'A peanut cross-section',
    'An almond cross-section',
    'A laundry lint knot',
    'A sugar-coated candy shell',
    'A tea leaf fragment',
  ],
  'chemistry-matter': [
    'A DNA double helix segment',
    'A buckyball molecule',
    'A caffeine molecule model',
    'A diamond lattice model',
    'An antibody protein',
    'A carbon nanotube',
    'A ribosome model',
    'A graphene sheet model',
    'A chlorophyll molecule model',
    'A zeolite cage',
    'A folded protein molecule',
    'A lithium ion battery separator',
    'A perovskite crystal cell',
    'A hemoglobin protein',
    'A liquid crystal droplet',
    'A nanoparticle cluster',
    'A quartz crystal point',
    'A dopamine molecule model',
    'A collagen triple helix',
    'A silica gel bead',
    'A water molecule model',
    'A vitamin C molecule model',
    'A penicillin molecule model',
    'An aspirin molecule model',
    'A serotonin molecule model',
    'A scent molecule model',
    'A graphite sheet model',
    'A glucose molecule model',
    'An enzyme active site',
    'An insulin molecule',
    'A RNA hairpin',
    'A nucleosome bead',
    'A lipid bilayer vesicle',
    'A polymer chain coil',
    'A nylon fiber molecule',
    'A polyethylene chain',
    'A crystal dendrite',
    'A rust flake on iron',
    'A copper patina crystal',
    'A catalyst pellet',
    'An activated carbon pore',
    'A charcoal pore structure',
    'A baking soda crystal',
    'A citric acid crystal',
    'A calcium carbonate crystal',
    'A hydroxyapatite bone mineral',
    'A magnetite crystal',
    'A sulfur crystal',
    'A gallium droplet',
    'A mercury droplet',
    'An aerogel fragment',
    'A flame soot particle',
    'A pyrite crystal cluster',
    'A sodium chloride crystal lattice',
    'A sucrose crystal cluster',
    'A fuel cell catalyst layer',
  ],
  'earth-weather': [
    'A volcano cutaway',
    'A geode cross-section',
    'A tornado funnel model',
    'A fulgurite lightning tube',
    'A fossil shark tooth',
    'A black smoker chimney',
    'A meteorite Widmanstatten slice',
    'A hurricane cloud spiral',
    'A mammoth tooth',
    'A subduction zone cutaway',
    'A malachite mineral sample',
    'A sinkhole cutaway',
    'A volcanic ash particle',
    'An ice core cylinder',
    'A lightning leader branch',
    'A manganese nodule',
    'A dinosaur footprint fossil',
    'An aurora curtain fold',
    'A lava bomb',
    'An obsidian shard',
    'A pumice stone',
    'A folded mountain cross-section',
    'A geyser cone cutaway',
    'A cave pearl',
    'A desert ventifact stone',
    'A sand dune ripple sample',
    'A river delta mini model',
    'A fossil ammonite',
    'A fossil fern leaf',
    'A basalt rock sample',
    'A granite rock sample',
    'A sandstone cross-section',
    'A limestone fossil fragment',
    'A shale layer sample',
    'A slate shard',
    'A marble vein sample',
    'A quartz crystal cluster',
    'A turquoise mineral nugget',
    'A tektite glass fragment',
    'A fault block model',
    'A mid-ocean ridge cutaway',
    'A stalactite',
    'A stalagmite',
    'A hailstone cross-section',
    'A snowflake crystal',
    'A thundercloud anvil model',
    'A mammatus cloud lobe',
    'A lenticular cloud lens',
    'A dust devil column',
    'A wildfire ember',
    'A pollen-coated raindrop',
    'A polar ice melt pond',
    'A permafrost ice wedge',
    'A mud crack polygon',
    'A landslide shear plane',
    'A tsunami wave cross-section',
  ],
  'space-time': [
    'A black hole accretion disk',
    'A Jupiter cutaway model',
    'A comet nucleus',
    'A neutron star model',
    'A trilobite compound eye fossil',
    'A supernova remnant shell',
    'A saber-toothed cat skull',
    'A Saturn moon Enceladus geyser',
    'A Mars rover wheel',
    'A dinosaur egg fossil',
    'A spiral galaxy core',
    'An icy moon Europa cross-section',
    'A solar flare loop',
    'A Tiktaalik fossil skull',
    'A spacesuit helmet',
    'A star cutaway',
    'A gravitational lens ring',
    'A pulsar beam model',
    'A red giant star cutaway',
    'A white dwarf star',
    'A planetary nebula shell',
    'A protoplanetary disk',
    'An asteroid fragment',
    'A chondrule in a meteorite',
    'A lunar crater model',
    'A Moon rock sample',
    'A Mars dust devil column',
    'A Mars polar ice cap model',
    'A Venus cloud layer model',
    'A Mercury cratered globe',
    "Jupiter's Great Red Spot vortex",
    'A Saturn ring particle',
    'A Titan methane lake droplet',
    'A Neptune storm vortex',
    'A Kuiper Belt object',
    'A globular star cluster',
    'A dark matter halo model',
    'A cosmic web node',
    'A sunspot cross-section',
    'A coronal mass ejection shell',
    'An aurora oval model',
    'A rocket capsule heat shield',
    'A satellite dish antenna',
    'A Hubble mirror segment',
    'A tyrannosaurus tooth',
    'A mammoth molar',
    'A whale skeleton',
    'An Archaeopteryx feather fossil',
    'A stromatolite dome',
    'A fossilized fern',
    'A Burgess Shale anomalocaris',
    'A Cambrian trilobite eye',
    'A pterosaur wing bone',
    'A fossilized coral',
    'A crinoid fossil stem',
    'A brachiopod shell fossil',
  ],
  'machines-systems': [
    'A rocket engine nozzle',
    'A mechanical watch escapement',
    'A jet engine turbine blade',
    'A camera lens stack',
    'A lithium battery cutaway',
    'A microscope objective lens',
    'A turbocharger compressor wheel',
    'A 3D printer nozzle',
    'A prosthetic knee joint',
    'A robotic gripper',
    'A microchip transistor layer',
    'A lock cylinder cutaway',
    'A hard drive platter head',
    'A catalytic converter honeycomb',
    'A syringe needle bevel',
    'A telescope mirror segment',
    'A ball bearing',
    'A water filter cartridge cutaway',
    'A camera sensor chip',
    'A silicon wafer die',
    'A CPU heat spreader cutaway',
    'A circuit board trace section',
    'A solder ball grid array',
    'A fiber optic cable cross-section',
    'A microphone capsule',
    'A speaker driver',
    'A headphone driver cutaway',
    'A vinyl record groove',
    'A cylindrical battery cell cutaway',
    'A pouch battery layer stack',
    'A solar cell cross-section',
    'A wind turbine blade root',
    'A heat pump compressor',
    'A refrigerator evaporator coil',
    'A reverse osmosis membrane',
    'An activated carbon filter granule',
    'A faucet aerator',
    'A gear tooth pair',
    'A bicycle chain link',
    'A bicycle brake caliper',
    'A car engine piston',
    'A spark plug',
    'A brake disc cross-section',
    'A tire tread block',
    'A rocket turbopump impeller',
    'A parachute cord weave',
    'A drone propeller',
    'A propeller blade',
    'A ship anchor fluke',
    'A submarine pressure hull cross-section',
    'A quartz watch crystal',
    'A key tooth profile',
    'A zipper tooth chain',
    'A sewing needle tip',
    'A ballpoint pen tip',
    'A fountain pen nib',
  ],
}
