#!/usr/bin/env node
// Regenerate src/shared/templates/catalog.ts by scanning the template module
// directories. Page templates live in ./pages/<id>.ts, deck templates in
// ./decks/<id>.ts; each exports a `Template`. Drop a module in either dir and
// re-run this script — it re-derives the import list + TEMPLATES array.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '../src/shared/templates')
const catalogPath = path.resolve(root, 'catalog.ts')
const DIRS = ['pages', 'decks']

// Preferred display order (ids). Pages lead (the primary use case), decks follow.
// Unlisted modules are appended alphabetically.
const ORDER = [
  // ── Personal ──
  'resume',
  'personal-site',
  'portfolio',
  'link-in-bio',
  'pet-page',
  'travel-journal',
  'wedding',
  // ── Marketing ──
  'landing-page',
  'pitch-onepager',
  'agency',
  'pricing',
  'coming-soon',
  'case-study',
  // ── Business ──
  'business-home',
  'restaurant',
  'course',
  'event-conf',
  // ── Writing ──
  'blog',
  'article',
  'recipe',
  'docs',
  'changelog',
  'product-spec',
  // ── Dashboards ──
  'analytics-dashboard',
  'financial-report',
  'crypto-dashboard',
  'fitness-stats',
  'weather',
  // ── Games ──
  'moldable-bird',
  'snake',
  'breakout',
  '2048',
  'memory',
  'quiz',
  // ── 3D / Motion ──
  'three-d-orb',
  'three-globe',
  'three-terrain',
  'particle-toy',
  // ── Slide decks (carried from Slides) ──
  'bold-founder',
  'editorial',
  'dark-tech',
  'finance-pro',
  'data-dashboard',
]

const mods = []
for (const dir of DIRS) {
  const abs = path.join(root, dir)
  if (!fs.existsSync(abs)) continue
  for (const f of fs.readdirSync(abs).filter((f) => f.endsWith('.ts'))) {
    const src = fs.readFileSync(path.join(abs, f), 'utf8')
    const exp = src.match(/export const (\w+)\s*:\s*Template\s*=/)
    const idm = src.match(/\bid:\s*'([^']+)'/)
    if (!exp || !idm) {
      console.warn(`! skipped ${dir}/${f} (no exported Template / id)`)
      continue
    }
    mods.push({
      dir,
      file: f.replace(/\.ts$/, ''),
      exportName: exp[1],
      id: idm[1],
    })
  }
}

mods.sort((a, b) => {
  const ia = ORDER.indexOf(a.id),
    ib = ORDER.indexOf(b.id)
  if (ia !== -1 && ib !== -1) return ia - ib
  if (ia !== -1) return -1
  if (ib !== -1) return 1
  return a.id.localeCompare(b.id)
})

const imports = mods
  .map((m) => `import { ${m.exportName} } from './${m.dir}/${m.file}'`)
  .join('\n')
const arr = mods.map((m) => `  ${m.exportName},`).join('\n')

const out = `// The template library — studio-grade. Each template lives in its own module:
// page artifacts under ./pages/<id>.ts, slide decks under ./decks/<id>.ts. Every
// module exports a \`Template\` with a self-contained, fully-built sample.
//
// GENERATED by scripts/build-catalog.mjs — do not hand-edit the lists below.
// To add a template: drop a module in ./pages/ or ./decks/, add its id to ORDER
// in the script, then run \`node scripts/build-catalog.mjs\`.

import type { Template } from './types'

${imports}

export const TEMPLATES: Template[] = [
${arr}
]
`

fs.writeFileSync(catalogPath, out)
console.log(`wired ${mods.length} templates -> catalog.ts`)
for (const m of mods) console.log(`  ${m.id.padEnd(24)} ${m.dir}/${m.file}`)
