import {
  HandHeart,
  Heart,
  Leaf,
  Mountain,
  ShieldCheck,
  Sun,
  Target,
  Users,
  Wind,
  Zap,
} from 'lucide-react'

export const categories = [
  {
    id: 'inner-peace',
    name: 'Inner Peace',
    icon: Wind,
    color: '#f0f9ff',
    accent: '#0ea5e9',
  },
  {
    id: 'self-love',
    name: 'Self Love',
    icon: Heart,
    color: '#fff1f2',
    accent: '#f43f5e',
  },
  {
    id: 'abundance',
    name: 'Abundance',
    icon: Leaf,
    color: '#ecfdf5',
    accent: '#10b981',
  },
  {
    id: 'courage',
    name: 'Courage',
    icon: Zap,
    color: '#fff7ed',
    accent: '#f59e0b',
  },
  {
    id: 'gratitude',
    name: 'Gratitude',
    icon: HandHeart,
    color: '#fffbeb',
    accent: '#fbbf24',
  },
  {
    id: 'healing',
    name: 'Healing',
    icon: ShieldCheck,
    color: '#f5f3ff',
    accent: '#8b5cf6',
  },
  {
    id: 'focus',
    name: 'Focus',
    icon: Target,
    color: '#f0fdfa',
    accent: '#14b8a6',
  },
  {
    id: 'social',
    name: 'Connection',
    icon: Users,
    color: '#fdf2f8',
    accent: '#ec4899',
  },
  {
    id: 'strength',
    name: 'Strength',
    icon: Mountain,
    color: '#f8fafc',
    accent: '#64748b',
  },
  { id: 'joy', name: 'Joy', icon: Sun, color: '#fefce8', accent: '#eab308' },
]

const affirmationTemplates: Record<string, string[]> = {
  'inner-peace': [
    'I am at peace with all that has happened, is happening, and will happen.',
    'My mind is calm and my heart is light.',
    'I release all tension and embrace the stillness within me.',
    'I am the architect of my own peace.',
    'Tranquility flows through every part of my being.',
    'I breathe in calm and I breathe out stress.',
    'I choose to respond with peace, even in chaos.',
    'Every breath I take fills me with serenity.',
    'My inner world is a sanctuary of calm.',
    'I let go of what I cannot control.',
    'I am grounded, stable, and secure.',
    'Peace begins with me.',
    'I radiate calm and tranquility to others.',
    'My thoughts are slow, soft, and gentle.',
    'I cultivate a quiet mind.',
    'I find stillness in the present moment.',
    'I release the need to rush through life.',
    'Serenity is my natural state.',
    'I am centered and balanced.',
    'I embrace silence as a source of strength.',
    'My soul is at rest.',
    'I let peace guide my decisions.',
    'I am free from worry and anxiety.',
    'I trust in the flow of life.',
    'Calmness washes over me like a gentle wave.',
    'I am patient with myself and others.',
    'I choose harmony over conflict.',
    'My heart beats with a peaceful rhythm.',
    'I find comfort in simplicity.',
    'I accept this moment exactly as it is.',
    'Stillness restores my spirit.',
    'I release all resistance and surrender to peace.',
    'My mind is a clear, calm lake.',
    'I am anchored in tranquility.',
    'I welcome peace into every cell of my body.',
    'I am unmoved by external chaos.',
    'I create space for quiet reflection.',
    'Peaceful thoughts come easily to me.',
    'I am a vessel of calm energy.',
    'I slow down and appreciate the present.',
    'I breathe deeply and feel at ease.',
    'My spirit is tranquil and undisturbed.',
    'I let go of tension with every exhale.',
    'I am comfortable with stillness.',
    'Peace is my priority.',
    'I move through life with grace and ease.',
    'My inner peace is unshakable.',
    'I find refuge in my own serenity.',
    'I am gentle with my thoughts.',
    'I embrace the quiet spaces in my day.',
    'Calm is my constant companion.',
    'I release the weight of yesterday.',
    'I am present, peaceful, and content.',
    'My nervous system is calm and regulated.',
    'I choose thoughts that bring me peace.',
    'I am relaxed in mind, body, and spirit.',
    'I let tranquility be my guide.',
    'I find peace in nature and simple pleasures.',
    'My soul is serene and steady.',
    'I am at home in the stillness.',
    'I release all need for struggle.',
    'Peace flows through me effortlessly.',
    'I am calm under pressure.',
    'I trust the timing of my life.',
    'I exhale stress and inhale calm.',
    'I am a peaceful presence in the world.',
    'My mind settles like still water.',
    'I nurture my inner peace daily.',
    'I choose serenity over stress.',
    'I am wrapped in a blanket of calm.',
    'I find balance in every breath.',
    'Peace is always available to me.',
    'I am grateful for moments of quiet.',
    'My thoughts drift gently like clouds.',
    'I am at ease with uncertainty.',
    'I cultivate an oasis of calm within.',
    'I let peace dissolve my worries.',
    'I am centered in my own stillness.',
    'My heart knows deep peace.',
    'I welcome rest and restoration.',
    'I am grounded in the present moment.',
    'Tranquility is my birthright.',
    'I move slowly and mindfully.',
    'I am free from the grip of anxiety.',
    'I breathe in peace, I breathe out love.',
    'My life unfolds peacefully.',
    'I find calm in the eye of any storm.',
    'I honor my need for rest.',
    'I am at peace with who I am.',
    'Stillness speaks to my soul.',
    'I carry peace wherever I go.',
    'I am calm, collected, and composed.',
    'I let go and let peace in.',
    'My energy is calm and steady.',
    'I rest in the arms of tranquility.',
    'I am deeply relaxed and at peace.',
    'I trust myself to find calm.',
    'I am a lighthouse of peace.',
    'Quiet moments nourish my soul.',
    'I am peaceful in thought and action.',
    'I embrace each moment with calm acceptance.',
    'I am whole, complete, and at peace.',
  ],
  'self-love': [
    'I am worthy of love and respect just as I am.',
    'I treat myself with the same kindness I show to others.',
    'My potential is limitless and I trust my journey.',
    'I am enough. I have always been enough.',
    'I celebrate my unique qualities and strengths.',
    'I forgive myself for my mistakes and grow from them.',
    'I am deserving of all the good things life has to offer.',
    'I love the person I am becoming.',
    'I am my own best friend.',
    'I nourish my soul with self-care.',
    'I honor my boundaries and my needs.',
    'I am proud of how far I have come.',
    'My worth is not defined by my productivity.',
    'I accept myself unconditionally.',
    'I speak to myself with compassion.',
    'I am beautiful inside and out.',
    'I deserve happiness and fulfillment.',
    'I embrace my imperfections as part of my uniqueness.',
    'I am allowed to take up space.',
    'My self-worth is inherent and unshakable.',
    'I choose to see the good in myself.',
    'I am gentle with myself when I struggle.',
    'I celebrate small victories.',
    'I give myself permission to rest.',
    'I am complete on my own.',
    'I trust my instincts and inner wisdom.',
    'I am learning to love myself more each day.',
    'I release the need for perfection.',
    'I am patient with my growth.',
    'My opinion of myself matters most.',
    'I am worthy of my own time and attention.',
    'I radiate self-confidence.',
    'I am comfortable in my own skin.',
    'I honor my feelings without judgment.',
    'I am resilient and capable.',
    'I choose self-love over self-criticism.',
    'I am grateful for my body and all it does for me.',
    'I let go of comparisons.',
    'I am a work in progress and that is beautiful.',
    'I deserve to be treated well, by myself and others.',
    'I am kind to myself in moments of doubt.',
    'I celebrate who I am today.',
    'I nourish my mind with positive thoughts.',
    'I am worthy of respect and love.',
    'I accept compliments graciously.',
    'I stand up for myself.',
    'I am allowed to change and grow.',
    'I trust the path I am on.',
    'I release shame and embrace self-acceptance.',
    'I am valuable just as I am.',
    'I give myself grace.',
    'I am proud of my authenticity.',
    'I welcome self-love into my life.',
    'I prioritize my mental health.',
    'I am not my mistakes.',
    'I choose to focus on my strengths.',
    'I speak kindly to myself.',
    'I am deserving of peace and happiness.',
    'I love myself unconditionally.',
    'I am allowed to set boundaries.',
    'I take care of my needs.',
    'I am growing into my best self.',
    'I honor my journey without comparison.',
    'I believe in myself.',
    'I am magnetic and worthy of good things.',
    'I release self-doubt and embrace confidence.',
    'I am worthy of success.',
    'I trust my abilities.',
    'I am lovable exactly as I am.',
    'I deserve love and I give love freely.',
    'I accept myself without conditions.',
    'I am becoming more confident every day.',
    'I let go of negative self-talk.',
    'I am strong and capable.',
    'I honor my unique path.',
    'I am worthy of taking up space in this world.',
    'I release the need to please everyone.',
    'I am at peace with my past.',
    'I choose myself.',
    'I am whole and complete.',
    'I deserve all the love I give to others.',
    'I am my own source of happiness.',
    'I embrace my individuality.',
    'I am worthy of my dreams.',
    'I let love in, starting with self-love.',
    'I am proud of the person I see in the mirror.',
    'I nurture myself daily.',
    'I am deserving of joy.',
    'I give myself permission to be happy.',
    'I accept all parts of myself.',
    'I am confident in who I am.',
    'I love my body and treat it with respect.',
    'I am a good person who deserves good things.',
    'I release judgment of myself.',
    'I embrace my emotions fully.',
    'I am worthy of all the beauty life offers.',
    'I take pride in my uniqueness.',
    'I am enough, exactly as I am.',
    'I celebrate my existence.',
    'I am deeply loved, starting with myself.',
    'I choose self-compassion every day.',
    'I am at home within myself.',
  ],
  abundance: [
    'I am a magnet for prosperity and abundance.',
    'Success and opportunity flow to me effortlessly.',
    'The universe is providing for me in unexpected ways.',
    'I have everything I need to create a life I love.',
    'Wealth flows to me in increasing amounts.',
    'I am open to receiving the gifts of the universe.',
    'My life is full of richness and meaning.',
    'I choose to see the abundance all around me.',
    'I attract success with ease.',
    'Money comes to me easily and frequently.',
    'I am worthy of financial freedom.',
    'Abundance is my natural state.',
    'I release all blocks to receiving prosperity.',
    'I am grateful for the wealth I already have.',
    'Opportunities are drawn to me.',
    'I live an abundant and fulfilling life.',
    'I am surrounded by abundance in all forms.',
    'I welcome new streams of income.',
    'I am financially secure and stable.',
    'Prosperity is flowing into my life.',
    'I trust that I will always have enough.',
    'I deserve to be wealthy and successful.',
    'I attract positive financial outcomes.',
    'I am aligned with the energy of abundance.',
    'I release scarcity thinking.',
    'Money supports my happiness and well-being.',
    'I am capable of creating great wealth.',
    'I celebrate the success of others.',
    'I am open to limitless possibilities.',
    'I am grateful for the abundance in my life.',
    'I attract wealth through positive thoughts.',
    'My income exceeds my expenses.',
    'I am a powerful creator of my reality.',
    'Financial success comes naturally to me.',
    'I believe in my ability to earn and grow wealth.',
    'Abundance flows freely through me.',
    'I release any fear around money.',
    'I am worthy of a prosperous life.',
    'I am generously rewarded for my work.',
    'I attract wealth-building opportunities.',
    'My actions create constant prosperity.',
    'I manage money wisely and joyfully.',
    'I am surrounded by prosperity.',
    'I am grateful for the money I receive.',
    'I use money to improve my life and others.',
    'I am confident in my financial future.',
    'Wealth expands my ability to help others.',
    'I think big and attract big results.',
    'I am at peace with my relationship with money.',
    'I deserve to be paid well for my skills.',
    'Abundance is drawn to my positive energy.',
    'I release all limiting beliefs about money.',
    'I attract lucrative opportunities.',
    'Financial abundance flows to me daily.',
    'I am creating a life of abundance.',
    'I am grateful for the prosperity I attract.',
    'I am a money magnet.',
    'My wallet is always full.',
    'I welcome wealth with open arms.',
    'I am destined for financial success.',
    'I am blessed with financial abundance.',
    'I receive money happily and gratefully.',
    'Prosperity follows me everywhere.',
    'I am open to unexpected sources of income.',
    'I trust the universe to provide for me.',
    'I attract resources that support my goals.',
    'I am worthy of a life of plenty.',
    'I release any guilt around being wealthy.',
    'Abundance multiplies in my life.',
    'I attract success in all areas of my life.',
    'I am financially empowered.',
    'My prosperity grows each day.',
    'I am grateful for the flow of money in my life.',
    'I am in harmony with wealth.',
    'I allow abundance to enter my life.',
    'I believe in my unlimited earning potential.',
    'I attract clients and customers easily.',
    'My business thrives and grows.',
    'I am rich in health, love, and happiness.',
    'I make smart financial decisions.',
    'I am thankful for my growing wealth.',
    'I release all resistance to abundance.',
    'I embrace a mindset of plenty.',
    'I am rewarded richly for my contributions.',
    'Money is a positive force in my life.',
    'I attract wealth through my creativity.',
    'I am a successful and abundant person.',
    'I trust that abundance is always available.',
    'I welcome financial growth.',
    'I deserve all the abundance I receive.',
    'I am living my most prosperous life.',
    'Wealth comes to me from multiple sources.',
    'I am grateful for the abundance I have and the abundance on its way.',
    'I think and act like a wealthy person.',
    'I am free from financial worry.',
    'I radiate abundance.',
    'I am blessed beyond measure.',
    'I claim my prosperity now.',
    'I am aligned with wealth and success.',
    'The universe supports my financial goals.',
    'I am always provided for.',
    'I live abundantly and give generously.',
  ],
  courage: [
    'I face my fears with strength and grace.',
    'I am brave enough to live the life I have imagined.',
    'Every challenge is an opportunity for growth.',
    'I trust my intuition to guide me through the unknown.',
    'I possess the power to change my story.',
    'Stepping out of my comfort zone leads to my greatest victories.',
    'I am resilient and I can handle whatever comes my way.',
    'I speak my truth even when my voice shakes.',
    'I am bold and fearless.',
    'I embrace uncertainty as part of the adventure.',
    'I have the courage to be imperfect.',
    'I trust myself to make the right decisions.',
    'I am not defined by my fears.',
    'I take action despite feeling afraid.',
    'I am confident in my ability to navigate challenges.',
    'I choose courage over comfort.',
    'I am stronger than my doubts.',
    'I welcome new experiences with an open heart.',
    'I stand tall in the face of adversity.',
    'I have the bravery to ask for what I need.',
    'I am the hero of my own story.',
    'I release fear and embrace possibility.',
    'I am worthy of taking risks.',
    'I grow braver each day.',
    'I have survived every challenge so far.',
    'I trust in my strength.',
    'I am fearless in pursuit of my dreams.',
    'I have the courage to begin again.',
    'I am not afraid to fail.',
    'I transform fear into fuel.',
    'I face each day with bravery.',
    'I am courageous in my vulnerability.',
    'I believe in my ability to overcome obstacles.',
    'I take bold steps toward my goals.',
    'I am empowered by my choices.',
    'I have the courage to let go of what no longer serves me.',
    'I stand firm in my convictions.',
    'I am brave enough to be authentic.',
    'I step into my power with courage.',
    'I am capable of handling anything life brings.',
    'I embrace challenges as opportunities to grow.',
    'I have the strength to face my fears head on.',
    'I act with courage and confidence.',
    'I am not limited by fear.',
    'I trust the journey even when I cannot see the destination.',
    'I have the courage to set healthy boundaries.',
    'I am bold in my actions and decisions.',
    'I release the fear of judgment.',
    'I am worthy of pursuing my passions.',
    'I find strength in uncertainty.',
    'I am courageous enough to be myself.',
    'I face the unknown with curiosity.',
    'I have the heart of a warrior.',
    'I take courageous action every day.',
    'I am not afraid to shine brightly.',
    'I embrace my inner strength.',
    'I have the bravery to start something new.',
    'I am a force of courage.',
    'I trust that I can handle whatever comes.',
    'I replace fear with faith.',
    'I am unstoppable.',
    'I leap and the net appears.',
    'I have the courage to love fully.',
    'I am braver than I believe.',
    'I step outside my comfort zone regularly.',
    'I am not held back by past failures.',
    'I have the strength to persevere.',
    'I am fierce and fearless.',
    'I choose action over hesitation.',
    'I have the courage to speak up.',
    'I face my fears and they dissolve.',
    'I am empowered by challenges.',
    'I rise each time I fall.',
    'I am daring and adventurous.',
    'I have the courage to change.',
    'I am comfortable with being uncomfortable.',
    'I embrace the unknown with excitement.',
    'I am not afraid of hard work.',
    'I trust my path even when it is unclear.',
    'I have the audacity to dream big.',
    'I am a courageous soul.',
    'I meet challenges with determination.',
    'I have the bravery to be different.',
    'I am strong in body, mind, and spirit.',
    'I face life with an open heart.',
    'I have the courage to admit when I am wrong.',
    'I stand up for what I believe in.',
    'I am not afraid of my own power.',
    'I embrace each new chapter with courage.',
    'I have the strength to endure.',
    'I take the leap of faith.',
    'I am fearless in my authenticity.',
    'I have the courage to chase my dreams.',
    'I trust my inner warrior.',
    'I am bold, brave, and brilliant.',
    'I have the heart to keep going.',
    'I face tomorrow without fear.',
    'I am a beacon of courage.',
    'I have the strength to say no.',
    'I step forward with confidence.',
    'I am courageous in every aspect of my life.',
  ],
  gratitude: [
    'I am grateful for the small joys that make life beautiful.',
    'Today I choose to focus on my blessings.',
    'Gratitude turns what I have into enough.',
    'I appreciate the people who support and love me.',
    'My heart is full of thanks for another day of life.',
    'I find beauty in the simplest moments.',
    "I am thankful for my health and my body's strength.",
    'The more I express gratitude, the more I find to be grateful for.',
    'I am grateful for this present moment.',
    'I appreciate the lessons in every experience.',
    'I am thankful for the roof over my head.',
    'I am grateful for the food that nourishes me.',
    'I appreciate my unique talents and abilities.',
    'I am thankful for the love in my life.',
    'Gratitude fills my heart each day.',
    'I am grateful for the gift of today.',
    'I appreciate my body and all it allows me to do.',
    'I am thankful for fresh air and clean water.',
    'I am grateful for the beauty of nature.',
    'I appreciate the kindness of strangers.',
    'I am thankful for the ability to learn and grow.',
    'I am grateful for my sense of humor.',
    'I appreciate the comfort of my home.',
    'I am thankful for peaceful moments.',
    'I am grateful for my memories.',
    'I appreciate the strength I have within me.',
    'I am thankful for new opportunities.',
    'I am grateful for the challenges that have shaped me.',
    'I appreciate my own resilience.',
    'I am thankful for the ability to feel emotions deeply.',
    'I am grateful for my senses.',
    'I appreciate the music that moves my soul.',
    'I am thankful for the changing seasons.',
    'I am grateful for laughter.',
    'I appreciate the warmth of the sun.',
    'I am thankful for friendships old and new.',
    'I am grateful for the ability to dream.',
    'I appreciate the technology that connects me to others.',
    'I am thankful for books and stories.',
    'I am grateful for the journey I am on.',
    'I appreciate quiet mornings.',
    'I am thankful for good conversations.',
    'I am grateful for the love of animals.',
    'I appreciate my own courage.',
    'I am thankful for second chances.',
    'I am grateful for my creativity.',
    'I appreciate the stars in the night sky.',
    'I am thankful for my family.',
    'I am grateful for the wisdom of others.',
    'I appreciate moments of stillness.',
    'I am thankful for the ability to give and receive love.',
    'I am grateful for my education.',
    'I appreciate my own growth over the years.',
    'I am thankful for the rain that nourishes the earth.',
    'I am grateful for cozy blankets.',
    'I appreciate the taste of good food.',
    'I am thankful for the gift of sight.',
    'I am grateful for the sound of laughter.',
    'I appreciate the freedom I have.',
    'I am thankful for a warm bed.',
    'I am grateful for the ocean.',
    'I appreciate the mountains and forests.',
    'I am thankful for acts of kindness.',
    'I am grateful for the ability to heal.',
    'I appreciate the time I have been given.',
    'I am thankful for art and creativity.',
    'I am grateful for mentors and teachers.',
    'I appreciate my past for shaping who I am.',
    'I am thankful for the future and its possibilities.',
    'I am grateful for my breath.',
    'I appreciate my heartbeat.',
    'I am thankful for restful sleep.',
    'I am grateful for my ability to walk.',
    'I appreciate the feeling of accomplishment.',
    'I am thankful for hugs.',
    'I am grateful for smiles from strangers.',
    'I appreciate the power of hope.',
    'I am thankful for the chance to try again.',
    'I am grateful for moments of clarity.',
    'I appreciate the strength to keep going.',
    'I am thankful for every sunrise.',
    'I am grateful for every sunset.',
    'I appreciate the gift of communication.',
    'I am thankful for my intuition.',
    'I am grateful for the ability to forgive.',
    'I appreciate my own patience.',
    'I am thankful for my connection to others.',
    'I am grateful for music and dance.',
    'I appreciate the simple pleasure of a cup of tea.',
    'I am thankful for the colors of the world.',
    'I am grateful for the people who inspire me.',
    'I appreciate the work that fulfills me.',
    'I am thankful for personal growth.',
    'I am grateful for the love I can share.',
    'I appreciate every day I am given.',
    'I am thankful for the peace in my heart.',
    'I am grateful for all that I have.',
    'I appreciate the journey as much as the destination.',
    'I am thankful for life itself.',
    'I am grateful beyond words.',
    'I live each day with deep gratitude.',
  ],
  healing: [
    'My body knows how to heal itself.',
    'I give myself permission to rest and recover.',
    'Every cell in my body is vibrating with health.',
    'I release old wounds and embrace new beginnings.',
    'I am patient with my healing process.',
    'Healing is happening for me right now.',
    'I am strong, resilient, and whole.',
    'I welcome wellness into every part of my life.',
    'I breathe in healing energy.',
    'My mind and body are in perfect harmony.',
    'I release any pain from my past.',
    'I am becoming stronger every day.',
    'I am surrounded by restorative light.',
    'I am a vessel of health and vitality.',
    "I trust my body's ability to heal.",
    'I nurture my body with love and care.',
    'I am healing on every level.',
    'I release stress and invite relaxation.',
    'My immune system is strong and healthy.',
    "I am in tune with my body's needs.",
    'I choose thoughts that support my healing.',
    'I am worthy of a healthy life.',
    'I embrace the healing power of rest.',
    'I am gentle with myself as I heal.',
    'My body regenerates and restores itself.',
    'I release emotional blocks to my health.',
    "I am grateful for my body's healing abilities.",
    'I am open to all forms of healing.',
    'I trust the process of recovery.',
    'I fill my mind with peaceful thoughts.',
    'I allow love to heal my wounds.',
    'I am patient with my body.',
    'I release toxins and embrace purity.',
    'I am connected to the healing energy of the earth.',
    'I treat my body as a temple.',
    'I am deserving of vibrant health.',
    'I listen to my body and honor its messages.',
    'I am healing physically, mentally, and emotionally.',
    'I forgive myself and others to promote healing.',
    'I nourish my body with healthy choices.',
    'I am at peace with my body.',
    'I visualize my body in perfect health.',
    'I release the past and embrace the present.',
    'I am whole and healthy.',
    'I trust that my body is doing its best.',
    'I support my healing with positive thoughts.',
    'I am calm and relaxed.',
    'I embrace each day as a step toward wellness.',
    'I am resilient and I recover quickly.',
    'I release fear and embrace healing.',
    'I am surrounded by love and support.',
    "I trust in my body's wisdom.",
    'I am patient and kind with myself.',
    'I invite balance into my life.',
    'I am worthy of complete healing.',
    'I let go of pain and welcome relief.',
    'I am healing from the inside out.',
    'I embrace the journey to wellness.',
    'I am filled with healing light.',
    'I release negativity and embrace positivity.',
    'I am open to miracles of healing.',
    'I am getting healthier every moment.',
    'I honor my need for rest and recovery.',
    'I am free from pain and discomfort.',
    'I embrace my body with love.',
    'I am connected to the source of all healing.',
    'I am renewing my body and mind.',
    'I release all that blocks my healing.',
    'I am grateful for my health journey.',
    'I trust my healing path.',
    'I am moving toward perfect health.',
    'I nourish my soul as well as my body.',
    'I am restored and renewed.',
    'I embrace the healing power of nature.',
    'I am at peace with my healing.',
    'I visualize myself in radiant health.',
    'I release tension from every muscle.',
    'I am healing with each breath I take.',
    'I am surrounded by healing energy.',
    'I embrace wellness in all its forms.',
    'I am grateful for the healing taking place.',
    'I trust that I am healing perfectly.',
    'I am filled with vitality and energy.',
    'I release old patterns that do not serve my health.',
    'I am aligned with perfect health.',
    "I embrace my body's natural healing rhythm.",
    'I am getting stronger every day.',
    'I trust my recovery process.',
    'I am healed, whole, and healthy.',
    'I invite peace into my body.',
    'I am patient as my body heals.',
    'I release illness and embrace wellness.',
    'I am becoming more vibrant each day.',
    "I honor my body's need for healing.",
    "I am grateful for my body's resilience.",
    'I am a healing miracle.',
    'I embrace every aspect of my recovery.',
    'I am worthy of perfect health.',
    'I am healed in body, mind, and spirit.',
    'I trust the timing of my healing.',
    'I am restored to full vitality.',
  ],
  focus: [
    'I am fully present in this moment.',
    'My mind is clear and focused.',
    'I direct my energy toward my goals.',
    'I accomplish tasks with ease and efficiency.',
    'I am disciplined and productive.',
    'I eliminate distractions effortlessly.',
    'I am in control of my attention.',
    'I prioritize what matters most.',
    'I complete what I start.',
    'My concentration is sharp and unwavering.',
    'I am committed to my goals.',
    'I stay on track with ease.',
    'I am organized and efficient.',
    'I focus on one thing at a time.',
    'I channel my thoughts productively.',
    'I am present and engaged.',
    'My mind is a powerful tool.',
    'I am capable of deep focus.',
    'I accomplish great things through focus.',
    'I am mindful of how I spend my time.',
    'I set clear goals and achieve them.',
    'I am determined and persistent.',
    'I give my full attention to what I am doing.',
    'I block out noise and stay centered.',
    'My focus brings me success.',
    'I am intentional with my actions.',
    'I finish tasks before starting new ones.',
    'I am sharp and alert.',
    'I stay motivated and driven.',
    'I choose focus over distraction.',
    'I am a master of my own attention.',
    'I thrive when I am focused.',
    'I approach challenges with clarity.',
    'I am productive and effective.',
    'I trust my ability to concentrate.',
    'I make steady progress every day.',
    'I am results-oriented.',
    'I give my best effort to every task.',
    'I am patient with long-term goals.',
    'I remain focused under pressure.',
    'I work with purpose and intention.',
    'I am consistent in my efforts.',
    'I take action toward my priorities.',
    'I am goal-driven and ambitious.',
    'I use my time wisely.',
    'I stay committed to my vision.',
    'I complete my work with excellence.',
    'I am focused on solutions.',
    'I easily enter a state of flow.',
    'I am deeply engaged in my work.',
    'I take breaks to recharge my focus.',
    'I am calm and collected.',
    'I work smarter, not harder.',
    'I maintain momentum on my projects.',
    'I am in the zone.',
    'I am dedicated to my success.',
    'I tune out distractions with ease.',
    'I am mentally strong and focused.',
    'I prioritize tasks effectively.',
    'I am capable of sustained concentration.',
    'I complete goals ahead of schedule.',
    'I am proactive in my work.',
    'I stay present and attentive.',
    'I create an environment that supports focus.',
    'I am locked in on my objectives.',
    'I take focused action every day.',
    'I am efficient with my energy.',
    'I handle multiple priorities with ease.',
    'I am laser-focused on what matters.',
    'I trust my ability to get things done.',
    'I am a high performer.',
    'I manage my time with skill.',
    'I am disciplined in my habits.',
    'I am wired for productivity.',
    'I break big goals into manageable steps.',
    'I am motivated by progress.',
    'I start each day with intention.',
    'I stay committed even when it is hard.',
    'I am unstoppable when focused.',
    'I make the most of every hour.',
    'I am in control of my schedule.',
    'I keep my eyes on the prize.',
    'I focus on what I can control.',
    'I am free from mental clutter.',
    'I achieve my goals with focused effort.',
    'I am engaged and energized.',
    'I make decisions quickly and confidently.',
    'I am organized in thought and action.',
    'I stay dedicated to my path.',
    'I eliminate unnecessary tasks.',
    'I am focused on the process.',
    'I take action without hesitation.',
    'I am a productivity machine.',
    'I accomplish more than I expect.',
    'I am mentally prepared for success.',
    'I honor my commitments to myself.',
    'I focus on excellence.',
    'I am relentless in pursuit of my goals.',
    "I maintain a winner's mindset.",
    'I am disciplined and determined.',
    'I harness my focus for success.',
  ],
  social: [
    'I attract positive and loving relationships.',
    'I am surrounded by people who uplift me.',
    'I communicate openly and honestly.',
    'I am a loyal and trustworthy friend.',
    'I deserve healthy, nurturing relationships.',
    'I connect deeply with others.',
    'I am valued and appreciated by my loved ones.',
    'I give and receive love freely.',
    'I build meaningful connections with ease.',
    'I am a source of joy to those around me.',
    'I am open to new friendships.',
    'I treat others with kindness and respect.',
    'I am an excellent listener.',
    'I foster harmony in my relationships.',
    'I am comfortable expressing my feelings.',
    'I attract people who respect my boundaries.',
    'I am worthy of deep, lasting love.',
    'I create space for healthy communication.',
    'I am patient with others.',
    'I embrace the differences in those I love.',
    'I am grateful for my support system.',
    'I am present in my interactions.',
    'I show appreciation for the people in my life.',
    'I am a positive presence.',
    'I resolve conflicts with grace.',
    'I am emotionally available.',
    'I build bridges instead of walls.',
    'I am honest and transparent.',
    'I nurture my relationships.',
    'I am a loving partner.',
    'I attract friendships that are mutually supportive.',
    'I am compassionate and understanding.',
    'I create safe spaces for others.',
    'I am open to love.',
    'I trust those who have earned my trust.',
    'I am confident in social situations.',
    'I listen to understand, not just to respond.',
    'I am grateful for the love in my life.',
    'I let go of toxic relationships.',
    'I attract healthy love.',
    'I am a good communicator.',
    'I support my loved ones unconditionally.',
    'I am warm and welcoming.',
    'I make others feel valued.',
    'I am comfortable being vulnerable.',
    'I embrace connection over isolation.',
    'I attract genuine people.',
    'I give love generously.',
    'I am a caring friend.',
    'I attract relationships that help me grow.',
    'I am loved for who I am.',
    'I show empathy toward others.',
    'I build trust over time.',
    'I am open to giving and receiving feedback.',
    'I approach relationships with an open heart.',
    'I am at ease in group settings.',
    'I am a team player.',
    'I celebrate the successes of others.',
    'I share my true self with those I trust.',
    "I am respectful of others' boundaries.",
    'I maintain healthy boundaries.',
    'I communicate my needs clearly.',
    'I attract love and friendship effortlessly.',
    'I am a magnet for meaningful relationships.',
    'I am comfortable asking for help.',
    'I appreciate the uniqueness of others.',
    'I bring out the best in people.',
    'I am a good judge of character.',
    'I foster trust and loyalty.',
    'I create loving relationships.',
    'I am at peace with my loved ones.',
    'I express gratitude to those who matter.',
    'I accept others as they are.',
    'I am surrounded by love.',
    'I cultivate understanding in my relationships.',
    'I am kind and thoughtful.',
    'I repair relationships with care.',
    'I show up fully for the people I love.',
    'I attract positive energy from others.',
    'I am confident in expressing love.',
    'I build a community that supports me.',
    'I am a healer in my relationships.',
    'I embrace the joy of togetherness.',
    'I am grateful for every connection I have.',
    'I radiate warmth and love.',
    'I give others the benefit of the doubt.',
    'I am a source of comfort.',
    'I communicate with clarity and compassion.',
    'I attract soulful connections.',
    'I am worthy of deep friendships.',
    'I treasure the moments I share with others.',
    'I am a positive influence.',
    'I honor the people in my life.',
    'I cultivate trust and intimacy.',
    'I forgive those who have hurt me.',
    'I am thankful for companionship.',
    'I love deeply and freely.',
    'I am connected to a loving community.',
    'I cherish the bonds I have formed.',
    'I am loved and I love in return.',
    'I am open to the magic of human connection.',
  ],
  strength: [
    'I am stronger than any obstacle in my path.',
    'I have the inner power to overcome anything.',
    'My strength is renewed with every breath.',
    'I stand firm in my truth and my power.',
    'I am capable of achieving my wildest dreams.',
    'I have the discipline to follow through.',
    'I am the master of my own destiny.',
    'I possess an iron will and a gentle heart.',
    'I rise above my challenges with grace.',
    'I am bold, brave, and unstoppable.',
    'My resilience is my superpower.',
    'I trust in my ability to survive and thrive.',
    'I am built to endure.',
    'I have the strength to carry on.',
    'I am unbreakable.',
    'I persevere through every storm.',
    'I am mentally and physically strong.',
    'I draw strength from within.',
    'I am anchored in my inner power.',
    'I have the fortitude to face any challenge.',
    'I stand tall no matter what.',
    'I am a pillar of strength.',
    'I recover quickly from setbacks.',
    'I am rooted in my values.',
    'I harness my strength for good.',
    'I am determined to succeed.',
    'I push through when times get tough.',
    'I am empowered by my experiences.',
    'I have the courage to keep going.',
    'I am a survivor.',
    'I am strengthened by adversity.',
    'I dig deep and find my power.',
    'I am tough and tenacious.',
    'I have the stamina to reach my goals.',
    'I am fierce in the face of fear.',
    'I transform obstacles into opportunities.',
    'I am a force of nature.',
    'I have the willpower to resist temptation.',
    'I am grounded and unshakable.',
    'I embrace my inner warrior.',
    'I am resilient in the face of change.',
    'I am relentless in my pursuit of growth.',
    'I am a tower of strength.',
    'I never give up.',
    'I am strong in mind and spirit.',
    'I have the power to change my life.',
    'I am forged by fire.',
    'I am dependable and strong.',
    'I carry my burdens with grace.',
    'I am capable of great endurance.',
    'I am not afraid of hard times.',
    'I rise stronger from every fall.',
    'I have the grit to succeed.',
    'I am unwavering in my resolve.',
    'I am powerful beyond measure.',
    'I embrace challenges as tests of strength.',
    'I am hardened by experience.',
    'I have the heart of a lion.',
    'I am unyielding in my beliefs.',
    'I am sustained by my inner strength.',
    'I thrive under pressure.',
    'I am built for this.',
    'I overcome every hurdle.',
    'I am solid and steady.',
    'I have the backbone to stand up for myself.',
    'I am tougher than I know.',
    'I am fueled by determination.',
    'I am a rock for those around me.',
    'I face my demons and win.',
    'I am indestructible.',
    'I am powered by purpose.',
    'I have the strength to start over.',
    'I am steadfast and true.',
    'I am resilient through and through.',
    'I have the muscle to move mountains.',
    'I am solid in my convictions.',
    'I weather every storm.',
    'I am a champion of my own life.',
    'I have reserves of strength I have not yet tapped.',
    'I am mighty.',
    'I am an immovable force.',
    'I have the power to persist.',
    'I am tempered by trials.',
    'I am a beacon of strength for others.',
    'I never back down.',
    'I am empowered by my struggles.',
    'I have the mettle to succeed.',
    'I am strong enough to ask for help.',
    'I am stalwart and dependable.',
    'I have the endurance to go the distance.',
    'I am unbowed.',
    'I have the vigor to keep fighting.',
    'I am sustained by hope.',
    'I am strong today and every day.',
    'I trust in my own power.',
    'I am a warrior.',
    'I am unafraid of the battle ahead.',
    'I have the strength to let go.',
    'I am victorious.',
    'I am the embodiment of strength.',
    'I am powerful, present, and persistent.',
  ],
  joy: [
    'I find joy in the smallest of miracles.',
    'Happiness is my natural state of being.',
    'I am surrounded by love and laughter.',
    'Today is a beautiful day to be alive.',
    'My heart is open to the wonders of the world.',
    'I radiate light and positivity wherever I go.',
    'I choose to see the sunny side of every situation.',
    'I am the creator of my own happiness.',
    'Everything is working out for my highest good.',
    'I attract delightful experiences.',
    'My life is a celebration.',
    'I smile and the world smiles with me.',
    'I am filled with vibrant energy and excitement.',
    'I embrace joy in all its forms.',
    'I am grateful for the happiness I feel today.',
    'I allow myself to feel pure joy.',
    'I spread happiness wherever I go.',
    'I find reasons to laugh every day.',
    'I am lighthearted and free.',
    'I attract positive and happy people.',
    'I choose joy over worry.',
    'I am playful and carefree.',
    'I find happiness in giving to others.',
    'I am at peace and full of joy.',
    'I let go of anything that dims my light.',
    'I am a source of happiness.',
    'I welcome fun and laughter into my life.',
    'I feel joy deep in my soul.',
    'I am energized by the beauty around me.',
    "I am delighted by life's surprises.",
    'I am cheerful and optimistic.',
    'I attract wonderful moments.',
    'I am content with who I am.',
    'I find bliss in the present.',
    'I am full of life.',
    'I am happy for no reason at all.',
    'I embrace every moment with joy.',
    'I feel alive and excited.',
    'I am open to all the happiness the universe offers.',
    'I am blessed with a joyful spirit.',
    'I laugh freely and often.',
    'I am uplifted by the good in the world.',
    'I find wonder in the everyday.',
    'I am happy to be me.',
    'I am bursting with positive energy.',
    'I celebrate my own happiness.',
    'I am cheerful in the face of challenges.',
    'I choose to focus on what brings me joy.',
    'I am surrounded by beauty and happiness.',
    'I feel gratitude and joy every day.',
    'I am at home in my happiness.',
    'I am alive with joy.',
    'I embrace the magic of each day.',
    'I am naturally happy.',
    'I take pleasure in simple things.',
    'I feel joyful from the moment I wake up.',
    'I am glowing with happiness.',
    'I find delight in learning new things.',
    'I attract moments of pure happiness.',
    'I am lighthearted and joyful.',
    'I celebrate the gift of life.',
    'I feel happiness bubbling up inside me.',
    'I am grateful for every happy memory.',
    'I am surrounded by positivity.',
    'I let happiness flow through me.',
    'I am a happy person.',
    'I find joy in connection with others.',
    'I am nourished by laughter.',
    'I feel joyful and free.',
    'I embrace a life of happiness.',
    'I am delighted to be here.',
    'I am happy with my life.',
    'I find joy even in difficult times.',
    'I am filled with warmth and happiness.',
    'I attract joyful experiences.',
    'I am a magnet for happiness.',
    'I am optimistic about the future.',
    'I feel happiness in my heart.',
    'I am happy to give and receive love.',
    'I radiate joy to everyone I meet.',
    'I find bliss in being myself.',
    'I am overflowing with happiness.',
    'I am at peace with the joy I feel.',
    'I am excited about my life.',
    'I welcome happiness with open arms.',
    'I am a beacon of joy.',
    'I feel deeply happy.',
    'I am smiling from the inside out.',
    'I am grateful for the joy in my life.',
    'I feel lighthearted and carefree.',
    'I embrace life with enthusiasm.',
    'I am full of positive emotions.',
    'I cherish every joyful moment.',
    'I am happy to be alive.',
    'I let joy lead the way.',
    'I am blessed with happiness.',
    'I feel uplifted and inspired.',
    'I attract endless joy.',
    'I am vibrantly happy.',
    'I choose happiness every single day.',
    'I am living a joyful life.',
  ],
}

export function getAffirmations(categoryId: string): string[] {
  return (
    affirmationTemplates[categoryId] || [
      'I am growing every day.',
      'I choose positivity.',
      'I am capable.',
      'My life is filled with light.',
    ]
  )
}
