import {
  Anchor,
  Compass,
  Feather,
  Flame,
  Flower2,
  HandHeart,
  Heart,
  HeartHandshake,
  Leaf,
  type LucideIcon,
  Mountain,
  Shield,
  ShieldCheck,
  Sprout,
  Sun,
  Sunrise,
  Target,
  Users,
  Wind,
  Zap,
} from 'lucide-react'

export interface Category {
  id: string
  name: string
  /** One-line invitation shown beneath the category name. */
  blurb: string
  icon: LucideIcon
  /**
   * The single source of truth for a category's color. Surfaces are derived
   * from this accent at low alpha via color-mix so they adapt to light and
   * dark themes — never paint a solid pale background.
   */
  accent: string
}

export const categories: Category[] = [
  {
    id: 'inner-peace',
    name: 'Inner Peace',
    blurb: 'Settle the mind, soften the body',
    icon: Wind,
    accent: '#0ea5e9',
  },
  {
    id: 'self-love',
    name: 'Self Love',
    blurb: 'Be your own kindest voice',
    icon: Heart,
    accent: '#f43f5e',
  },
  {
    id: 'abundance',
    name: 'Abundance',
    blurb: 'Open up to what flows toward you',
    icon: Leaf,
    accent: '#10b981',
  },
  {
    id: 'courage',
    name: 'Courage',
    blurb: 'Move forward, fear and all',
    icon: Zap,
    accent: '#f59e0b',
  },
  {
    id: 'gratitude',
    name: 'Gratitude',
    blurb: 'Notice the good already here',
    icon: HandHeart,
    accent: '#fbbf24',
  },
  {
    id: 'healing',
    name: 'Healing',
    blurb: 'Give yourself room to mend',
    icon: ShieldCheck,
    accent: '#8b5cf6',
  },
  {
    id: 'focus',
    name: 'Focus',
    blurb: 'Return to what matters now',
    icon: Target,
    accent: '#14b8a6',
  },
  {
    id: 'social',
    name: 'Connection',
    blurb: 'Draw closer to your people',
    icon: Users,
    accent: '#ec4899',
  },
  {
    id: 'strength',
    name: 'Strength',
    blurb: 'Stand steady through anything',
    icon: Mountain,
    accent: '#64748b',
  },
  {
    id: 'joy',
    name: 'Joy',
    blurb: 'Let the light back in',
    icon: Sun,
    accent: '#eab308',
  },
  {
    id: 'confidence',
    name: 'Confidence',
    blurb: 'Trust your own voice',
    icon: Flame,
    accent: '#f97316',
  },
  {
    id: 'resilience',
    name: 'Resilience',
    blurb: 'Bend without breaking',
    icon: Anchor,
    accent: '#0891b2',
  },
  {
    id: 'growth',
    name: 'Growth',
    blurb: 'Become who you are meant to be',
    icon: Sprout,
    accent: '#22c55e',
  },
  {
    id: 'letting-go',
    name: 'Letting Go',
    blurb: 'Release what you cannot hold',
    icon: Feather,
    accent: '#a78bfa',
  },
  {
    id: 'presence',
    name: 'Presence',
    blurb: 'Arrive in this moment',
    icon: Flower2,
    accent: '#06b6d4',
  },
  {
    id: 'purpose',
    name: 'Purpose',
    blurb: 'Live by what matters',
    icon: Compass,
    accent: '#6366f1',
  },
  {
    id: 'boundaries',
    name: 'Boundaries',
    blurb: 'Protect your peace',
    icon: Shield,
    accent: '#ef4444',
  },
  {
    id: 'forgiveness',
    name: 'Forgiveness',
    blurb: 'Set down the weight of resentment',
    icon: HeartHandshake,
    accent: '#fb7185',
  },
  {
    id: 'hope',
    name: 'Hope',
    blurb: 'Trust the morning is coming',
    icon: Sunrise,
    accent: '#fb923c',
  },
]

const affirmationTemplates: Record<string, string[]> = {
  'inner-peace': [
    'I am at peace with all that has happened, is happening, and will happen.',
    'My mind is calm and my heart is light.',
    'I release all tension and embrace the stillness within me.',
    'I am the architect of my own peace.',
    'Tranquility flows through every part of my being.',
    'I breathe in calm and I breathe out stress.',
    'I choose to respond with peace, even in chaos.',
    'Every breath I take fills me with serenity.',
    'My inner world is a sanctuary of calm.',
    'I let go of what I cannot control.',
    'I am grounded, stable, and secure.',
    'Peace begins with me.',
    'I radiate calm and tranquility to others.',
    'My thoughts are slow, soft, and gentle.',
    'I cultivate a quiet mind.',
    'I find stillness in the present moment.',
    'I release the need to rush through life.',
    'Serenity is my natural state.',
    'I am centered and balanced.',
    'I embrace silence as a source of strength.',
    'My soul is at rest.',
    'I let peace guide my decisions.',
    'I am free from worry and anxiety.',
    'I trust in the flow of life.',
    'Calmness washes over me like a gentle wave.',
    'I am patient with myself and others.',
    'I choose harmony over conflict.',
    'My heart beats with a peaceful rhythm.',
    'I find comfort in simplicity.',
    'I accept this moment exactly as it is.',
    'Stillness restores my spirit.',
    'I release all resistance and surrender to peace.',
    'My mind is a clear, calm lake.',
    'I am anchored in tranquility.',
    'I welcome peace into every cell of my body.',
    'I am unmoved by external chaos.',
    'I create space for quiet reflection.',
    'Peaceful thoughts come easily to me.',
    'I am a vessel of calm energy.',
    'I slow down and appreciate the present.',
    'I breathe deeply and feel at ease.',
    'My spirit is tranquil and undisturbed.',
    'I let go of tension with every exhale.',
    'I am comfortable with stillness.',
    'Peace is my priority.',
    'I move through life with grace and ease.',
    'My inner peace is unshakable.',
    'I find refuge in my own serenity.',
    'I am gentle with my thoughts.',
    'I embrace the quiet spaces in my day.',
    'Calm is my constant companion.',
    'I release the weight of yesterday.',
    'I am present, peaceful, and content.',
    'My nervous system is calm and regulated.',
    'I choose thoughts that bring me peace.',
    'I am relaxed in mind, body, and spirit.',
    'I let tranquility be my guide.',
    'I find peace in nature and simple pleasures.',
    'My soul is serene and steady.',
    'I am at home in the stillness.',
    'I release all need for struggle.',
    'Peace flows through me effortlessly.',
    'I am calm under pressure.',
    'I trust the timing of my life.',
    'I exhale stress and inhale calm.',
    'I am a peaceful presence in the world.',
    'My mind settles like still water.',
    'I nurture my inner peace daily.',
    'I choose serenity over stress.',
    'I am wrapped in a blanket of calm.',
    'I find balance in every breath.',
    'Peace is always available to me.',
    'I am grateful for moments of quiet.',
    'My thoughts drift gently like clouds.',
    'I am at ease with uncertainty.',
    'I cultivate an oasis of calm within.',
    'I let peace dissolve my worries.',
    'I am centered in my own stillness.',
    'My heart knows deep peace.',
    'I welcome rest and restoration.',
    'I am grounded in the present moment.',
    'Tranquility is my birthright.',
    'I move slowly and mindfully.',
    'I am free from the grip of anxiety.',
    'I breathe in peace, I breathe out love.',
    'My life unfolds peacefully.',
    'I find calm in the eye of any storm.',
    'I honor my need for rest.',
    'I am at peace with who I am.',
    'Stillness speaks to my soul.',
    'I carry peace wherever I go.',
    'I am calm, collected, and composed.',
    'I let go and let peace in.',
    'My energy is calm and steady.',
    'I rest in the arms of tranquility.',
    'I am deeply relaxed and at peace.',
    'I trust myself to find calm.',
    'I am a lighthouse of peace.',
    'Quiet moments nourish my soul.',
    'I am peaceful in thought and action.',
    'I embrace each moment with calm acceptance.',
    'I am whole, complete, and at peace.',
    'I am allowed to feel unsettled and still treat myself with patience while it passes.',
    'My anxiety is not an emergency to fix but a frightened part of me asking to be held.',
    'I let my shoulders drop, my jaw soften, and my breath fall lower than worry usually lets it go.',
    'Peace is not the absence of the storm but my willingness to stop bracing against the wind.',
    'I release my grip on outcomes I was never holding up in the first place.',
    'When my mind races into a hundred futures, I bring it back to the one body breathing here.',
    'I can be afraid and steady at once; fear does not get the final word on how I carry myself.',
    'I no longer mistake exhaustion for calm or numbness for peace.',
    'Some days the quiet is hard-won, and I honor the work it took to arrive here.',
    'I let things stay unfinished, unanswered, and uncertain without rushing to resolve the ache.',
    'I am learning I do not have to earn rest by suffering for it first.',
    'The part of me that wants to control everything is only trying to keep me safe, and I thank it before I set it down.',
    'I return to my breath the way the tide returns to shore, without shame for how far I drifted.',
    'I give myself permission to have no opinion, no reaction, and no plan for this moment.',
    'I meet my own anxiety the way I would meet a trembling animal: slowly, kindly, without sudden moves.',
    'I am coming home to myself room by room, lighting the places I had left in the dark.',
    'Not everything urgent is important, and I can let the urgency pass through without obeying it.',
    'I trust my body to remember how to soften even when my mind has forgotten.',
    'I lay down the exhausting belief that my vigilance is what holds the world together.',
    'Today I am a calm presence in my own life, not a visitor passing through it.',
    'I can hold grief and gratitude in the same hand without forcing either to leave.',
    'I forgive myself for the years I confused control with love and tension with care.',
    'Peace does not wait for my problems to be solved; it only asks that I stop abandoning myself in the middle of them.',
    'I am slowly unclenching from a lifetime of expecting the worst, one ordinary safe moment at a time.',
    'I have nothing to prove in this breath.',
    'Rest is not a reward; it is my right.',
    'I let the silence fill me instead of rushing to drown it out.',
    'Underneath the noise I am still here, and I am still whole.',
  ],
  'self-love': [
    'I am worthy of love and respect just as I am.',
    'I treat myself with the same kindness I show to others.',
    'My potential is limitless and I trust my journey.',
    'I am enough. I have always been enough.',
    'I celebrate my unique qualities and strengths.',
    'I forgive myself for my mistakes and grow from them.',
    'I am deserving of all the good things life has to offer.',
    'I love the person I am becoming.',
    'I am my own best friend.',
    'I nourish my soul with self-care.',
    'I honor my boundaries and my needs.',
    'I am proud of how far I have come.',
    'My worth is not defined by my productivity.',
    'I accept myself unconditionally.',
    'I speak to myself with compassion.',
    'I am beautiful inside and out.',
    'I deserve happiness and fulfillment.',
    'I embrace my imperfections as part of my uniqueness.',
    'I am allowed to take up space.',
    'My self-worth is inherent and unshakable.',
    'I choose to see the good in myself.',
    'I am gentle with myself when I struggle.',
    'I celebrate small victories.',
    'I give myself permission to rest.',
    'I am complete on my own.',
    'I trust my instincts and inner wisdom.',
    'I am learning to love myself more each day.',
    'I release the need for perfection.',
    'I am patient with my growth.',
    'My opinion of myself matters most.',
    'I am worthy of my own time and attention.',
    'I radiate self-confidence.',
    'I am comfortable in my own skin.',
    'I honor my feelings without judgment.',
    'I am resilient and capable.',
    'I choose self-love over self-criticism.',
    'I am grateful for my body and all it does for me.',
    'I let go of comparisons.',
    'I am a work in progress and that is beautiful.',
    'I deserve to be treated well, by myself and others.',
    'I am kind to myself in moments of doubt.',
    'I celebrate who I am today.',
    'I nourish my mind with positive thoughts.',
    'I am worthy of respect and love.',
    'I accept compliments graciously.',
    'I stand up for myself.',
    'I am allowed to change and grow.',
    'I trust the path I am on.',
    'I release shame and embrace self-acceptance.',
    'I am valuable just as I am.',
    'I give myself grace.',
    'I am proud of my authenticity.',
    'I welcome self-love into my life.',
    'I prioritize my mental health.',
    'I am not my mistakes.',
    'I choose to focus on my strengths.',
    'I speak kindly to myself.',
    'I am deserving of peace and happiness.',
    'I love myself unconditionally.',
    'I am allowed to set boundaries.',
    'I take care of my needs.',
    'I am growing into my best self.',
    'I honor my journey without comparison.',
    'I believe in myself.',
    'I am magnetic and worthy of good things.',
    'I release self-doubt and embrace confidence.',
    'I am worthy of success.',
    'I trust my abilities.',
    'I am lovable exactly as I am.',
    'I deserve love and I give love freely.',
    'I accept myself without conditions.',
    'I am becoming more confident every day.',
    'I let go of negative self-talk.',
    'I am strong and capable.',
    'I honor my unique path.',
    'I am worthy of taking up space in this world.',
    'I release the need to please everyone.',
    'I am at peace with my past.',
    'I choose myself.',
    'I am whole and complete.',
    'I deserve all the love I give to others.',
    'I am my own source of happiness.',
    'I embrace my individuality.',
    'I am worthy of my dreams.',
    'I let love in, starting with self-love.',
    'I am proud of the person I see in the mirror.',
    'I nurture myself daily.',
    'I am deserving of joy.',
    'I give myself permission to be happy.',
    'I accept all parts of myself.',
    'I am confident in who I am.',
    'I love my body and treat it with respect.',
    'I am a good person who deserves good things.',
    'I release judgment of myself.',
    'I embrace my emotions fully.',
    'I am worthy of all the beauty life offers.',
    'I take pride in my uniqueness.',
    'I am enough, exactly as I am.',
    'I celebrate my existence.',
    'I am deeply loved, starting with myself.',
    'I choose self-compassion every day.',
    'I am at home within myself.',
    'I am worthy of love on the days I produce nothing and prove nothing.',
    'My worth was never something I earned, so it is not something I can lose.',
    'I am learning to speak to myself the way I would speak to someone I am afraid of losing.',
    'When shame shows up, I do not have to hand it the keys to the whole house.',
    'I let myself be a work in progress without treating myself like a problem to be solved.',
    'Some days the bravest, kindest thing I do is simply refuse to abandon myself.',
    'I am allowed to take up space, to have needs, and to occasionally be inconvenient.',
    'I forgive the version of me who only knew what they knew at the time.',
    'I do not have to feel good about my body to treat it gently today.',
    'The harsh voice in my head is not the truth; it is only an old habit wearing my own accent.',
    'I can hold my disappointment and my tenderness in the same two hands.',
    'I am still worthy of rest even when the work is unfinished.',
    'I am curious about my mistakes instead of cruel about them.',
    'I lay down the belief that I must be useful in order to deserve to exist.',
    'Being hard on myself never made me better; it only made me tired, so I am setting it down.',
    'I am allowed to like myself before I become whoever I am trying to be.',
    'I meet my own sadness without rushing to fix it or explain it away.',
    'I am not behind in some invisible race; I am exactly where a life like mine arrives.',
    'When I fail, I lose a moment, not my belonging to myself.',
    'I let myself be loved as I actually am, not as I perform.',
    'The parts of me I have worked hardest to hide are still allowed to come home.',
    'I can be deeply flawed and deeply worth caring for, and neither one cancels the other.',
    'I am learning that softening toward myself is a form of courage, not a failure of nerve.',
    'I let my own breath remind me that I do not have to earn the next moment of my life.',
    'I treat my exhaustion as information, not as a character flaw.',
    'On the days I cannot believe I am enough, I can still choose to act as if I matter.',
    'I no longer apologize for tending to the one life I was given.',
    'I am allowed to outgrow the smallness I once mistook for humility.',
    'I am allowed to be proud of how I have survived, even the parts no one saw.',
  ],
  abundance: [
    'I am a magnet for prosperity and abundance.',
    'Success and opportunity flow to me effortlessly.',
    'The universe is providing for me in unexpected ways.',
    'I have everything I need to create a life I love.',
    'Wealth flows to me in increasing amounts.',
    'I am open to receiving the gifts of the universe.',
    'My life is full of richness and meaning.',
    'I choose to see the abundance all around me.',
    'I attract success with ease.',
    'Money comes to me easily and frequently.',
    'I am worthy of financial freedom.',
    'Abundance is my natural state.',
    'I release all blocks to receiving prosperity.',
    'I am grateful for the wealth I already have.',
    'Opportunities are drawn to me.',
    'I live an abundant and fulfilling life.',
    'I am surrounded by abundance in all forms.',
    'I welcome new streams of income.',
    'I am financially secure and stable.',
    'Prosperity is flowing into my life.',
    'I trust that I will always have enough.',
    'I deserve to be wealthy and successful.',
    'I attract positive financial outcomes.',
    'I am aligned with the energy of abundance.',
    'I release scarcity thinking.',
    'Money supports my happiness and well-being.',
    'I am capable of creating great wealth.',
    'I celebrate the success of others.',
    'I am open to limitless possibilities.',
    'I am grateful for the abundance in my life.',
    'I attract wealth through positive thoughts.',
    'My income exceeds my expenses.',
    'I am a powerful creator of my reality.',
    'Financial success comes naturally to me.',
    'I believe in my ability to earn and grow wealth.',
    'Abundance flows freely through me.',
    'I release any fear around money.',
    'I am worthy of a prosperous life.',
    'I am generously rewarded for my work.',
    'I attract wealth-building opportunities.',
    'My actions create constant prosperity.',
    'I manage money wisely and joyfully.',
    'I am surrounded by prosperity.',
    'I am grateful for the money I receive.',
    'I use money to improve my life and others.',
    'I am confident in my financial future.',
    'Wealth expands my ability to help others.',
    'I think big and attract big results.',
    'I am at peace with my relationship with money.',
    'I deserve to be paid well for my skills.',
    'Abundance is drawn to my positive energy.',
    'I release all limiting beliefs about money.',
    'I attract lucrative opportunities.',
    'Financial abundance flows to me daily.',
    'I am creating a life of abundance.',
    'I am grateful for the prosperity I attract.',
    'I am a money magnet.',
    'My wallet is always full.',
    'I welcome wealth with open arms.',
    'I am destined for financial success.',
    'I am blessed with financial abundance.',
    'I receive money happily and gratefully.',
    'Prosperity follows me everywhere.',
    'I am open to unexpected sources of income.',
    'I trust the universe to provide for me.',
    'I attract resources that support my goals.',
    'I am worthy of a life of plenty.',
    'I release any guilt around being wealthy.',
    'Abundance multiplies in my life.',
    'I attract success in all areas of my life.',
    'I am financially empowered.',
    'My prosperity grows each day.',
    'I am grateful for the flow of money in my life.',
    'I am in harmony with wealth.',
    'I allow abundance to enter my life.',
    'I believe in my unlimited earning potential.',
    'I attract clients and customers easily.',
    'My business thrives and grows.',
    'I am rich in health, love, and happiness.',
    'I make smart financial decisions.',
    'I am thankful for my growing wealth.',
    'I release all resistance to abundance.',
    'I embrace a mindset of plenty.',
    'I am rewarded richly for my contributions.',
    'Money is a positive force in my life.',
    'I attract wealth through my creativity.',
    'I am a successful and abundant person.',
    'I trust that abundance is always available.',
    'I welcome financial growth.',
    'I deserve all the abundance I receive.',
    'I am living my most prosperous life.',
    'Wealth comes to me from multiple sources.',
    'I am grateful for the abundance I have and the abundance on its way.',
    'I think and act like a wealthy person.',
    'I am free from financial worry.',
    'I radiate abundance.',
    'I am blessed beyond measure.',
    'I claim my prosperity now.',
    'I am aligned with wealth and success.',
    'The universe supports my financial goals.',
    'I am always provided for.',
    'I live abundantly and give generously.',
    'I am allowed to want more than survival, and the wanting does not make me greedy.',
    "There is room in this world for my dreams without taking the air from anyone else's.",
    "I release the old math that says someone else's win must be subtracted from mine.",
    'When envy rises, I let it point to what I quietly long for instead of letting it shame me.',
    'My worth is not a prize waiting at the finish line; it is the ground I am already standing on.',
    'I choose an ambition that grows from love, not from the dread of being left behind.',
    'I am learning to receive — a compliment, a hand, an hour of rest, a sum of money — without flinching or apologizing.',
    'Success is mine to define, and I will not measure my one life with a ruler someone else handed me.',
    'I trust that the effort I am pouring out now is not lost, even when I cannot yet see where it lands.',
    'Scarcity taught me to grab and to hoard, and I am gently loosening the grip one finger at a time.',
    'I deserve good things not because I have suffered enough to earn them, but simply because I am here.',
    'I can hold gratitude for what I have and honest hunger for what I want in the very same breath.',
    'I let go of the story that I must struggle visibly to prove that I am serious.',
    'When something good arrives, I practice staying with it instead of bracing for it to be taken away.',
    'My pace is not a flaw to be corrected; it is the true rhythm my life actually runs on.',
    'I am not behind — I am exactly as far as my own particular road has carried me.',
    'I let myself imagine a future so generous it frightens me a little.',
    'The abundance I am after is not only money; it is time, attention, and the freedom to choose.',
    'I forgive myself for the seasons I chased the wrong thing, and I let that chase become a teacher.',
    'I do not have to earn my rest by first running myself into the ground.',
    'Wealth that costs me my peace is not the kind of wealth I am building.',
    'I can be deeply ambitious and deeply patient at once; these two are not enemies.',
    'I notice the quiet abundance already here — a warm room, a full breath, someone who knows my name.',
    'I keep tending the work, trusting that what is meant to grow is already taking root underground.',
    'I am worthy of a life that feels spacious, even on the days that spaciousness feels far away.',
    'I stop treating my own goodness as something I must keep re-earning by how much I produce.',
    'Some days my abundance is small and ordinary, and I let small and ordinary be enough.',
    'I open my hands, because nothing good has ever been able to reach a fist.',
  ],
  courage: [
    'I face my fears with strength and grace.',
    'I am brave enough to live the life I have imagined.',
    'Every challenge is an opportunity for growth.',
    'I trust my intuition to guide me through the unknown.',
    'I possess the power to change my story.',
    'Stepping out of my comfort zone leads to my greatest victories.',
    'I am resilient and I can handle whatever comes my way.',
    'I speak my truth even when my voice shakes.',
    'I am bold and fearless.',
    'I embrace uncertainty as part of the adventure.',
    'I have the courage to be imperfect.',
    'I trust myself to make the right decisions.',
    'I am not defined by my fears.',
    'I take action despite feeling afraid.',
    'I am confident in my ability to navigate challenges.',
    'I choose courage over comfort.',
    'I am stronger than my doubts.',
    'I welcome new experiences with an open heart.',
    'I stand tall in the face of adversity.',
    'I have the bravery to ask for what I need.',
    'I am the hero of my own story.',
    'I release fear and embrace possibility.',
    'I am worthy of taking risks.',
    'I grow braver each day.',
    'I have survived every challenge so far.',
    'I trust in my strength.',
    'I am fearless in pursuit of my dreams.',
    'I have the courage to begin again.',
    'I am not afraid to fail.',
    'I transform fear into fuel.',
    'I face each day with bravery.',
    'I am courageous in my vulnerability.',
    'I believe in my ability to overcome obstacles.',
    'I take bold steps toward my goals.',
    'I am empowered by my choices.',
    'I have the courage to let go of what no longer serves me.',
    'I stand firm in my convictions.',
    'I am brave enough to be authentic.',
    'I step into my power with courage.',
    'I am capable of handling anything life brings.',
    'I embrace challenges as opportunities to grow.',
    'I have the strength to face my fears head on.',
    'I act with courage and confidence.',
    'I am not limited by fear.',
    'I trust the journey even when I cannot see the destination.',
    'I have the courage to set healthy boundaries.',
    'I am bold in my actions and decisions.',
    'I release the fear of judgment.',
    'I am worthy of pursuing my passions.',
    'I find strength in uncertainty.',
    'I am courageous enough to be myself.',
    'I face the unknown with curiosity.',
    'I have the heart of a warrior.',
    'I take courageous action every day.',
    'I am not afraid to shine brightly.',
    'I embrace my inner strength.',
    'I have the bravery to start something new.',
    'I am a force of courage.',
    'I trust that I can handle whatever comes.',
    'I replace fear with faith.',
    'I am unstoppable.',
    'I leap and the net appears.',
    'I have the courage to love fully.',
    'I am braver than I believe.',
    'I step outside my comfort zone regularly.',
    'I am not held back by past failures.',
    'I have the strength to persevere.',
    'I am fierce and fearless.',
    'I choose action over hesitation.',
    'I have the courage to speak up.',
    'I face my fears and they dissolve.',
    'I am empowered by challenges.',
    'I rise each time I fall.',
    'I am daring and adventurous.',
    'I have the courage to change.',
    'I am comfortable with being uncomfortable.',
    'I embrace the unknown with excitement.',
    'I am not afraid of hard work.',
    'I trust my path even when it is unclear.',
    'I have the audacity to dream big.',
    'I am a courageous soul.',
    'I meet challenges with determination.',
    'I have the bravery to be different.',
    'I am strong in body, mind, and spirit.',
    'I face life with an open heart.',
    'I have the courage to admit when I am wrong.',
    'I stand up for what I believe in.',
    'I am not afraid of my own power.',
    'I embrace each new chapter with courage.',
    'I have the strength to endure.',
    'I take the leap of faith.',
    'I am fearless in my authenticity.',
    'I have the courage to chase my dreams.',
    'I trust my inner warrior.',
    'I am bold, brave, and brilliant.',
    'I have the heart to keep going.',
    'I face tomorrow without fear.',
    'I am a beacon of courage.',
    'I have the strength to say no.',
    'I step forward with confidence.',
    'I am courageous in every aspect of my life.',
    'I feel the fear move through my chest, and I take the step while it is still there — courage was never the absence of fear, only my willingness to bring it along.',
    'I let my voice shake while it tells the truth, because a trembling honesty is braver than a steady performance.',
    'I am afraid and I am capable in the same breath; these two have always shared a body, and that body is mine.',
    'When every nerve wants me to disappear, I choose to stay in the room and let myself be seen.',
    'I bet on myself today — not because I am sure I will win, but because I refuse to become the person who never let me try.',
    'My tenderness is not the weak spot I have to guard; it is the doorway everything real has to walk through.',
    'I say the thing I have been swallowing for weeks, plainly and without apology, and I trust myself to outlast whatever it stirs up.',
    'I stop waiting to feel ready, because readiness only ever arrives after I have already begun.',
    'I let people see the unfinished version of me, the one still working it out, and I watch them soften instead of leave.',
    'There is a quiet, stubborn part of me that keeps showing up no matter what, and today I finally call that part brave.',
    'I name out loud what I actually want, even when wanting it leaves me feeling exposed and small.',
    'I do not need to be fearless to be free; I only need to stop letting fear cast the deciding vote.',
    'I forgive the years I stayed silent, and I let that old ache become the reason I speak now.',
    'When my heart slams before the brave thing, I read it as proof this matters to me, not as a warning to turn back.',
    'I choose the clean discomfort of growing over the dull, familiar ache of staying exactly where I am.',
    "I can hold someone's disappointment without abandoning myself to make it disappear.",
    'I ask for what I need in plain words, and I let go of the exhausting hope that someone will simply guess.',
    'Today I do one thing that scares me — small enough to be possible, real enough to count.',
    'I trust that I can survive the answer, even when the answer is no; what I could never survive was not asking at all.',
    'I stop performing fine when I am breaking, because the truth, finally spoken, is its own kind of relief.',
    'I let myself be a beginner in front of other people — clumsy, learning, alive — rather than stay safely, quietly small.',
    'I choose the risk of being truly known over the long, careful loneliness of being safely hidden.',
    "I release the version of me that needed everyone's approval, and I make room for the one who can stand alone in a room and still feel whole.",
    'When the old voice insists I am not enough, I keep walking, and I let my actions do the answering.',
    'I have already lived through harder things than this, and I let that quiet record steady my hands.',
    'I begin before I believe I can, and I let the believing catch up to me on the way.',
    'I meet the part of me that wants to run with real tenderness, and then I gently ask it to stay just a little longer.',
    'I let courage be small today — one honest sentence, one unanswered question asked, one foot set down on ground I cannot yet see.',
  ],
  gratitude: [
    'I am grateful for the small joys that make life beautiful.',
    'Today I choose to focus on my blessings.',
    'Gratitude turns what I have into enough.',
    'I appreciate the people who support and love me.',
    'My heart is full of thanks for another day of life.',
    'I find beauty in the simplest moments.',
    "I am thankful for my health and my body's strength.",
    'The more I express gratitude, the more I find to be grateful for.',
    'I am grateful for this present moment.',
    'I appreciate the lessons in every experience.',
    'I am thankful for the roof over my head.',
    'I am grateful for the food that nourishes me.',
    'I appreciate my unique talents and abilities.',
    'I am thankful for the love in my life.',
    'Gratitude fills my heart each day.',
    'I am grateful for the gift of today.',
    'I appreciate my body and all it allows me to do.',
    'I am thankful for fresh air and clean water.',
    'I am grateful for the beauty of nature.',
    'I appreciate the kindness of strangers.',
    'I am thankful for the ability to learn and grow.',
    'I am grateful for my sense of humor.',
    'I appreciate the comfort of my home.',
    'I am thankful for peaceful moments.',
    'I am grateful for my memories.',
    'I appreciate the strength I have within me.',
    'I am thankful for new opportunities.',
    'I am grateful for the challenges that have shaped me.',
    'I appreciate my own resilience.',
    'I am thankful for the ability to feel emotions deeply.',
    'I am grateful for my senses.',
    'I appreciate the music that moves my soul.',
    'I am thankful for the changing seasons.',
    'I am grateful for laughter.',
    'I appreciate the warmth of the sun.',
    'I am thankful for friendships old and new.',
    'I am grateful for the ability to dream.',
    'I appreciate the technology that connects me to others.',
    'I am thankful for books and stories.',
    'I am grateful for the journey I am on.',
    'I appreciate quiet mornings.',
    'I am thankful for good conversations.',
    'I am grateful for the love of animals.',
    'I appreciate my own courage.',
    'I am thankful for second chances.',
    'I am grateful for my creativity.',
    'I appreciate the stars in the night sky.',
    'I am thankful for my family.',
    'I am grateful for the wisdom of others.',
    'I appreciate moments of stillness.',
    'I am thankful for the ability to give and receive love.',
    'I am grateful for my education.',
    'I appreciate my own growth over the years.',
    'I am thankful for the rain that nourishes the earth.',
    'I am grateful for cozy blankets.',
    'I appreciate the taste of good food.',
    'I am thankful for the gift of sight.',
    'I am grateful for the sound of laughter.',
    'I appreciate the freedom I have.',
    'I am thankful for a warm bed.',
    'I am grateful for the ocean.',
    'I appreciate the mountains and forests.',
    'I am thankful for acts of kindness.',
    'I am grateful for the ability to heal.',
    'I appreciate the time I have been given.',
    'I am thankful for art and creativity.',
    'I am grateful for mentors and teachers.',
    'I appreciate my past for shaping who I am.',
    'I am thankful for the future and its possibilities.',
    'I am grateful for my breath.',
    'I appreciate my heartbeat.',
    'I am thankful for restful sleep.',
    'I am grateful for my ability to walk.',
    'I appreciate the feeling of accomplishment.',
    'I am thankful for hugs.',
    'I am grateful for smiles from strangers.',
    'I appreciate the power of hope.',
    'I am thankful for the chance to try again.',
    'I am grateful for moments of clarity.',
    'I appreciate the strength to keep going.',
    'I am thankful for every sunrise.',
    'I am grateful for every sunset.',
    'I appreciate the gift of communication.',
    'I am thankful for my intuition.',
    'I am grateful for the ability to forgive.',
    'I appreciate my own patience.',
    'I am thankful for my connection to others.',
    'I am grateful for music and dance.',
    'I appreciate the simple pleasure of a cup of tea.',
    'I am thankful for the colors of the world.',
    'I am grateful for the people who inspire me.',
    'I appreciate the work that fulfills me.',
    'I am thankful for personal growth.',
    'I am grateful for the love I can share.',
    'I appreciate every day I am given.',
    'I am thankful for the peace in my heart.',
    'I am grateful for all that I have.',
    'I appreciate the journey as much as the destination.',
    'I am thankful for life itself.',
    'I am grateful beyond words.',
    'I live each day with deep gratitude.',
    'I notice the small unremarkable things—the warmth of the mug, the light along the wall—and find they were never small at all.',
    'To be alive, breathing, and here is already more than I thought to ask for.',
    'Before I reach for what comes next, I pause to taste what is already in my hands.',
    'I give thanks for the people who showed up quietly, without applause, and changed the shape of my days.',
    'Gratitude does not ask me to pretend the hard parts away; I hold the ache and the appreciation in the same breath.',
    'The lessons I resented while living them taught me what comfort never could, and I bow to them now.',
    'I let the plain fact of waking be enough to soften me before the day asks anything of me.',
    'I savor my food slowly enough to remember it came from soil and rain, from hands and time.',
    'I notice the privileges I had stopped seeing—clean water, a roof, a door that locks—and let them surprise me again.',
    'I do not need more to be grateful; I need only to look more closely at what is already here.',
    'I thank the version of me who endured the seasons I was certain I would not survive.',
    'I am grateful for the people I have lost, because grief is only the shadow cast by how much they mattered.',
    'Even my difficulties have left me something: a deeper patience, a softer heart, a truer sense of what holds.',
    'I honor the long, unseen chain of strangers whose work makes my smallest comforts possible.',
    'I let myself be moved by beauty I did not make and cannot keep—the sky, the trees, a passing kindness.',
    'Even on a hard day I can find one true thing to be thankful for, and I let that one thing steady me.',
    'I choose to be astonished by the ordinary rather than numbed by it.',
    'I am grateful for unfinished things, because they mean my life is still in motion and still mine.',
    'I notice my breath rising and falling without my asking, and I am quietly amazed.',
    'I receive this day as something on loan, and so I hold it with both hands and an open palm.',
    'Thank you.',
    'I let contentment find me here, in an ordinary afternoon, exactly as things are.',
    'Gratitude is a practice and not a performance; I return to it even on the days it feels out of reach.',
    'I am grateful for the chance to begin again—today, and as many times as I need to.',
  ],
  healing: [
    'My body knows how to heal itself.',
    'I give myself permission to rest and recover.',
    'Every cell in my body is vibrating with health.',
    'I release old wounds and embrace new beginnings.',
    'I am patient with my healing process.',
    'Healing is happening for me right now.',
    'I am strong, resilient, and whole.',
    'I welcome wellness into every part of my life.',
    'I breathe in healing energy.',
    'My mind and body are in perfect harmony.',
    'I release any pain from my past.',
    'I am becoming stronger every day.',
    'I am surrounded by restorative light.',
    'I am a vessel of health and vitality.',
    "I trust my body's ability to heal.",
    'I nurture my body with love and care.',
    'I am healing on every level.',
    'I release stress and invite relaxation.',
    'My immune system is strong and healthy.',
    "I am in tune with my body's needs.",
    'I choose thoughts that support my healing.',
    'I am worthy of a healthy life.',
    'I embrace the healing power of rest.',
    'I am gentle with myself as I heal.',
    'My body regenerates and restores itself.',
    'I release emotional blocks to my health.',
    "I am grateful for my body's healing abilities.",
    'I am open to all forms of healing.',
    'I trust the process of recovery.',
    'I fill my mind with peaceful thoughts.',
    'I allow love to heal my wounds.',
    'I am patient with my body.',
    'I release toxins and embrace purity.',
    'I am connected to the healing energy of the earth.',
    'I treat my body as a temple.',
    'I am deserving of vibrant health.',
    'I listen to my body and honor its messages.',
    'I am healing physically, mentally, and emotionally.',
    'I forgive myself and others to promote healing.',
    'I nourish my body with healthy choices.',
    'I am at peace with my body.',
    'I visualize my body in perfect health.',
    'I release the past and embrace the present.',
    'I am whole and healthy.',
    'I trust that my body is doing its best.',
    'I support my healing with positive thoughts.',
    'I am calm and relaxed.',
    'I embrace each day as a step toward wellness.',
    'I am resilient and I recover quickly.',
    'I release fear and embrace healing.',
    'I am surrounded by love and support.',
    "I trust in my body's wisdom.",
    'I am patient and kind with myself.',
    'I invite balance into my life.',
    'I am worthy of complete healing.',
    'I let go of pain and welcome relief.',
    'I am healing from the inside out.',
    'I embrace the journey to wellness.',
    'I am filled with healing light.',
    'I release negativity and embrace positivity.',
    'I am open to miracles of healing.',
    'I am getting healthier every moment.',
    'I honor my need for rest and recovery.',
    'I am free from pain and discomfort.',
    'I embrace my body with love.',
    'I am connected to the source of all healing.',
    'I am renewing my body and mind.',
    'I release all that blocks my healing.',
    'I am grateful for my health journey.',
    'I trust my healing path.',
    'I am moving toward perfect health.',
    'I nourish my soul as well as my body.',
    'I am restored and renewed.',
    'I embrace the healing power of nature.',
    'I am at peace with my healing.',
    'I visualize myself in radiant health.',
    'I release tension from every muscle.',
    'I am healing with each breath I take.',
    'I am surrounded by healing energy.',
    'I embrace wellness in all its forms.',
    'I am grateful for the healing taking place.',
    'I trust that I am healing perfectly.',
    'I am filled with vitality and energy.',
    'I release old patterns that do not serve my health.',
    'I am aligned with perfect health.',
    "I embrace my body's natural healing rhythm.",
    'I am getting stronger every day.',
    'I trust my recovery process.',
    'I am healed, whole, and healthy.',
    'I invite peace into my body.',
    'I am patient as my body heals.',
    'I release illness and embrace wellness.',
    'I am becoming more vibrant each day.',
    "I honor my body's need for healing.",
    "I am grateful for my body's resilience.",
    'I am a healing miracle.',
    'I embrace every aspect of my recovery.',
    'I am worthy of perfect health.',
    'I am healed in body, mind, and spirit.',
    'I trust the timing of my healing.',
    'I am restored to full vitality.',
    'My body has carried me through every single day I have ever lived, and today I meet it with gratitude instead of a verdict.',
    'I am allowed to rest before I have earned it, because rest is not a wage but a need.',
    'Healing does not move in a straight line, and the days I slip backward are not failures but part of the path.',
    'I let myself eat in a way that nourishes me, treating hunger as information rather than an enemy to defeat.',
    'Some wounds are still tender, and I can say so honestly without pretending I am further along than I am.',
    'I am learning to thank my body for the work it does in silence: my heartbeat, my breath, the slow repair I never see.',
    'When I stop to rest, I am not falling behind; I am giving my mind and body the conditions they need to mend.',
    'I release the belief that my worth is measured by how much I produce in a day.',
    'Grief and joy can live in me at once, and I do not have to resolve one to make room for the other.',
    'I treat my hunger, my tiredness, and my tears as honest messengers rather than inconveniences.',
    'I forgive my body for the ways it has struggled, knowing it was never working against me.',
    'On the hard days, I lower the bar and simply keep myself company.',
    'I let myself receive care without believing I have to immediately repay it.',
    'The pain I carry is real, and naming it gently is the first kindness I can offer myself.',
    'I am allowed to outgrow the version of me that survived by ignoring its own needs.',
    'I drink water, I eat slowly, I sleep when I am tired, and I call this self-respect rather than indulgence.',
    'My emotions are not problems to be solved but weather to be felt and let move through.',
    'I will not rush my own recovery to make other people more comfortable.',
    'Setbacks do not erase the progress beneath them; the ground I have gained is still mine.',
    'I am tender with the parts of me that are still afraid, because fear is almost always guarding an old hurt.',
    'I let go of the timeline I imagined for my healing and trust the slower, truer pace of my own becoming.',
    'I can hold compassion for who I was in my hardest seasons, even for the choices I would not make again.',
    'My body is not a project to be perfected but a home to be lived in and cared for.',
    'I allow myself to feel a little better without bracing for it to be taken away.',
    'Nourishment is more than food; it is sunlight, stillness, an honest conversation, and the way I speak to myself when no one is listening.',
    'I am healing in ways I cannot yet see, the way a wound knits beneath the skin long before the scar fades.',
    'What happened to me was not my fault, and what I do with it now can still be my own.',
    'I no longer abandon myself to keep the peace with people who were never going to keep it with me.',
  ],
  focus: [
    'I am fully present in this moment.',
    'My mind is clear and focused.',
    'I direct my energy toward my goals.',
    'I accomplish tasks with ease and efficiency.',
    'I am disciplined and productive.',
    'I eliminate distractions effortlessly.',
    'I am in control of my attention.',
    'I prioritize what matters most.',
    'I complete what I start.',
    'My concentration is sharp and unwavering.',
    'I am committed to my goals.',
    'I stay on track with ease.',
    'I am organized and efficient.',
    'I focus on one thing at a time.',
    'I channel my thoughts productively.',
    'I am present and engaged.',
    'My mind is a powerful tool.',
    'I am capable of deep focus.',
    'I accomplish great things through focus.',
    'I am mindful of how I spend my time.',
    'I set clear goals and achieve them.',
    'I am determined and persistent.',
    'I give my full attention to what I am doing.',
    'I block out noise and stay centered.',
    'My focus brings me success.',
    'I am intentional with my actions.',
    'I finish tasks before starting new ones.',
    'I am sharp and alert.',
    'I stay motivated and driven.',
    'I choose focus over distraction.',
    'I am a master of my own attention.',
    'I thrive when I am focused.',
    'I approach challenges with clarity.',
    'I am productive and effective.',
    'I trust my ability to concentrate.',
    'I make steady progress every day.',
    'I am results-oriented.',
    'I give my best effort to every task.',
    'I am patient with long-term goals.',
    'I remain focused under pressure.',
    'I work with purpose and intention.',
    'I am consistent in my efforts.',
    'I take action toward my priorities.',
    'I am goal-driven and ambitious.',
    'I use my time wisely.',
    'I stay committed to my vision.',
    'I complete my work with excellence.',
    'I am focused on solutions.',
    'I easily enter a state of flow.',
    'I am deeply engaged in my work.',
    'I take breaks to recharge my focus.',
    'I am calm and collected.',
    'I work smarter, not harder.',
    'I maintain momentum on my projects.',
    'I am in the zone.',
    'I am dedicated to my success.',
    'I tune out distractions with ease.',
    'I am mentally strong and focused.',
    'I prioritize tasks effectively.',
    'I am capable of sustained concentration.',
    'I complete goals ahead of schedule.',
    'I am proactive in my work.',
    'I stay present and attentive.',
    'I create an environment that supports focus.',
    'I am locked in on my objectives.',
    'I take focused action every day.',
    'I am efficient with my energy.',
    'I handle multiple priorities with ease.',
    'I am laser-focused on what matters.',
    'I trust my ability to get things done.',
    'I am a high performer.',
    'I manage my time with skill.',
    'I am disciplined in my habits.',
    'I am wired for productivity.',
    'I break big goals into manageable steps.',
    'I am motivated by progress.',
    'I start each day with intention.',
    'I stay committed even when it is hard.',
    'I am unstoppable when focused.',
    'I make the most of every hour.',
    'I am in control of my schedule.',
    'I keep my eyes on the prize.',
    'I focus on what I can control.',
    'I am free from mental clutter.',
    'I achieve my goals with focused effort.',
    'I am engaged and energized.',
    'I make decisions quickly and confidently.',
    'I am organized in thought and action.',
    'I stay dedicated to my path.',
    'I eliminate unnecessary tasks.',
    'I am focused on the process.',
    'I take action without hesitation.',
    'I am a productivity machine.',
    'I accomplish more than I expect.',
    'I am mentally prepared for success.',
    'I honor my commitments to myself.',
    'I focus on excellence.',
    'I am relentless in pursuit of my goals.',
    "I maintain a winner's mindset.",
    'I am disciplined and determined.',
    'I harness my focus for success.',
  ],
  social: [
    'I attract positive and loving relationships.',
    'I am surrounded by people who uplift me.',
    'I communicate openly and honestly.',
    'I am a loyal and trustworthy friend.',
    'I deserve healthy, nurturing relationships.',
    'I connect deeply with others.',
    'I am valued and appreciated by my loved ones.',
    'I give and receive love freely.',
    'I build meaningful connections with ease.',
    'I am a source of joy to those around me.',
    'I am open to new friendships.',
    'I treat others with kindness and respect.',
    'I am an excellent listener.',
    'I foster harmony in my relationships.',
    'I am comfortable expressing my feelings.',
    'I attract people who respect my boundaries.',
    'I am worthy of deep, lasting love.',
    'I create space for healthy communication.',
    'I am patient with others.',
    'I embrace the differences in those I love.',
    'I am grateful for my support system.',
    'I am present in my interactions.',
    'I show appreciation for the people in my life.',
    'I am a positive presence.',
    'I resolve conflicts with grace.',
    'I am emotionally available.',
    'I build bridges instead of walls.',
    'I am honest and transparent.',
    'I nurture my relationships.',
    'I am a loving partner.',
    'I attract friendships that are mutually supportive.',
    'I am compassionate and understanding.',
    'I create safe spaces for others.',
    'I am open to love.',
    'I trust those who have earned my trust.',
    'I am confident in social situations.',
    'I listen to understand, not just to respond.',
    'I am grateful for the love in my life.',
    'I let go of toxic relationships.',
    'I attract healthy love.',
    'I am a good communicator.',
    'I support my loved ones unconditionally.',
    'I am warm and welcoming.',
    'I make others feel valued.',
    'I am comfortable being vulnerable.',
    'I embrace connection over isolation.',
    'I attract genuine people.',
    'I give love generously.',
    'I am a caring friend.',
    'I attract relationships that help me grow.',
    'I am loved for who I am.',
    'I show empathy toward others.',
    'I build trust over time.',
    'I am open to giving and receiving feedback.',
    'I approach relationships with an open heart.',
    'I am at ease in group settings.',
    'I am a team player.',
    'I celebrate the successes of others.',
    'I share my true self with those I trust.',
    "I am respectful of others' boundaries.",
    'I maintain healthy boundaries.',
    'I communicate my needs clearly.',
    'I attract love and friendship effortlessly.',
    'I am a magnet for meaningful relationships.',
    'I am comfortable asking for help.',
    'I appreciate the uniqueness of others.',
    'I bring out the best in people.',
    'I am a good judge of character.',
    'I foster trust and loyalty.',
    'I create loving relationships.',
    'I am at peace with my loved ones.',
    'I express gratitude to those who matter.',
    'I accept others as they are.',
    'I am surrounded by love.',
    'I cultivate understanding in my relationships.',
    'I am kind and thoughtful.',
    'I repair relationships with care.',
    'I show up fully for the people I love.',
    'I attract positive energy from others.',
    'I am confident in expressing love.',
    'I build a community that supports me.',
    'I am a healer in my relationships.',
    'I embrace the joy of togetherness.',
    'I am grateful for every connection I have.',
    'I radiate warmth and love.',
    'I give others the benefit of the doubt.',
    'I am a source of comfort.',
    'I communicate with clarity and compassion.',
    'I attract soulful connections.',
    'I am worthy of deep friendships.',
    'I treasure the moments I share with others.',
    'I am a positive influence.',
    'I honor the people in my life.',
    'I cultivate trust and intimacy.',
    'I forgive those who have hurt me.',
    'I am thankful for companionship.',
    'I love deeply and freely.',
    'I am connected to a loving community.',
    'I cherish the bonds I have formed.',
    'I am loved and I love in return.',
    'I am open to the magic of human connection.',
    'I belong here, not because I earned my place, but because I am here, breathing and present, and that turns out to be enough.',
    'I let people see the parts of me I usually hide, trusting that being known is worth the risk of being misunderstood.',
    'When loneliness arrives, I treat it not as proof that I am unlovable but as a quiet signal that I am ready to reach toward someone.',
    'I am allowed to need other people without calling it weakness, because needing each other is the oldest thing we know how to do.',
    'I can love someone all the way and still keep myself, because closeness was never supposed to cost me my own outline.',
    'I am learning to receive care without rushing to repay it, letting kindness simply land somewhere inside me and stay.',
    'Even on the days I feel invisible, I am held by bonds I cannot feel in the moment and do not always remember.',
    'I choose to stay soft in a world that rewards armor, because tenderness is the small door that real connection walks through.',
    'I forgive myself for the relationships that ended, and I let them keep teaching me how I want to love next.',
    'I do not have to perform to be wanted; the people meant for me stay for who I am, not for who I work to seem.',
    'I let myself be the first to reach out, to say I miss you, to admit I was wrong, because connection is worth more than my pride.',
    'When someone offers me their attention, I let myself believe I deserve it instead of bracing for the moment they leave.',
    'I am allowed to outgrow relationships that ask me to shrink, and I can release them with gratitude instead of guilt.',
    'I notice the small ways people show they care, and I let those quiet gestures slowly convince me I am not alone.',
    'I can sit with someone in their pain without trying to fix it, because sometimes presence is the only thing that heals.',
    'I am building relationships where I can say I am not okay and be met with steadiness instead of distance.',
    'My worth to the people I love is not measured by how useful I am or how little room I take up.',
    'I let myself be celebrated even when it makes me squirm, because being seen in my joy is its own kind of closeness.',
    'I trust that the people who love me can hold the whole truth of me, so I stop editing myself down to keep them comfortable.',
    'I set down the belief that I am a burden and make room for the chance that I am someone people are simply glad to know.',
    'Connection asks me to be brave far more often than it asks me to be perfect, and I am choosing brave.',
    'I am learning that distance does not erase love, and that some bonds hold quietly across silence and years.',
    'When I feel the pull to withdraw, I gently ask whether I am protecting myself or just afraid, and I choose the honest answer.',
    'I give the love I most long to receive, and in the giving I slowly learn how to let it in.',
    'I am one link in a long chain of people who have loved and been loved, and I was never meant to carry this life alone.',
    'I let conversations end without resolving everything, trusting that real intimacy can survive an open question.',
    'I stop keeping score in the people I love, because the relationships that last are not ledgers but a shared and ongoing grace.',
  ],
  strength: [
    'I am stronger than any obstacle in my path.',
    'I have the inner power to overcome anything.',
    'My strength is renewed with every breath.',
    'I stand firm in my truth and my power.',
    'I am capable of achieving my wildest dreams.',
    'I have the discipline to follow through.',
    'I am the master of my own destiny.',
    'I possess an iron will and a gentle heart.',
    'I rise above my challenges with grace.',
    'I am bold, brave, and unstoppable.',
    'My resilience is my superpower.',
    'I trust in my ability to survive and thrive.',
    'I am built to endure.',
    'I have the strength to carry on.',
    'I am unbreakable.',
    'I persevere through every storm.',
    'I am mentally and physically strong.',
    'I draw strength from within.',
    'I am anchored in my inner power.',
    'I have the fortitude to face any challenge.',
    'I stand tall no matter what.',
    'I am a pillar of strength.',
    'I recover quickly from setbacks.',
    'I am rooted in my values.',
    'I harness my strength for good.',
    'I am determined to succeed.',
    'I push through when times get tough.',
    'I am empowered by my experiences.',
    'I have the courage to keep going.',
    'I am a survivor.',
    'I am strengthened by adversity.',
    'I dig deep and find my power.',
    'I am tough and tenacious.',
    'I have the stamina to reach my goals.',
    'I am fierce in the face of fear.',
    'I transform obstacles into opportunities.',
    'I am a force of nature.',
    'I have the willpower to resist temptation.',
    'I am grounded and unshakable.',
    'I embrace my inner warrior.',
    'I am resilient in the face of change.',
    'I am relentless in my pursuit of growth.',
    'I am a tower of strength.',
    'I never give up.',
    'I am strong in mind and spirit.',
    'I have the power to change my life.',
    'I am forged by fire.',
    'I am dependable and strong.',
    'I carry my burdens with grace.',
    'I am capable of great endurance.',
    'I am not afraid of hard times.',
    'I rise stronger from every fall.',
    'I have the grit to succeed.',
    'I am unwavering in my resolve.',
    'I am powerful beyond measure.',
    'I embrace challenges as tests of strength.',
    'I am hardened by experience.',
    'I have the heart of a lion.',
    'I am unyielding in my beliefs.',
    'I am sustained by my inner strength.',
    'I thrive under pressure.',
    'I am built for this.',
    'I overcome every hurdle.',
    'I am solid and steady.',
    'I have the backbone to stand up for myself.',
    'I am tougher than I know.',
    'I am fueled by determination.',
    'I am a rock for those around me.',
    'I face my demons and win.',
    'I am indestructible.',
    'I am powered by purpose.',
    'I have the strength to start over.',
    'I am steadfast and true.',
    'I am resilient through and through.',
    'I have the muscle to move mountains.',
    'I am solid in my convictions.',
    'I weather every storm.',
    'I am a champion of my own life.',
    'I have reserves of strength I have not yet tapped.',
    'I am mighty.',
    'I am an immovable force.',
    'I have the power to persist.',
    'I am tempered by trials.',
    'I am a beacon of strength for others.',
    'I never back down.',
    'I am empowered by my struggles.',
    'I have the mettle to succeed.',
    'I am strong enough to ask for help.',
    'I am stalwart and dependable.',
    'I have the endurance to go the distance.',
    'I am unbowed.',
    'I have the vigor to keep fighting.',
    'I am sustained by hope.',
    'I am strong today and every day.',
    'I trust in my own power.',
    'I am a warrior.',
    'I am unafraid of the battle ahead.',
    'I have the strength to let go.',
    'I am victorious.',
    'I am the embodiment of strength.',
    'I am powerful, present, and persistent.',
    'I have survived every single one of my worst days, and that is not luck but a quiet, unbroken record of my own endurance.',
    'I am stronger than I feel, and the proof is simple: I am still here, still breathing, still reading these words.',
    'The weight I carry has not crushed me; it has shown me exactly how much my arms can hold.',
    'I do not have to feel strong to be strong, because some of my bravest days have looked, from the inside, like barely hanging on.',
    'I can set the heavy thing down for a while without believing I have failed for needing to rest.',
    'The hard seasons did not break me into pieces; they taught me what I am actually made of.',
    'I am the same person who got through the night I swore I could not get through, and that person is still living in me.',
    'I honor how tired I am instead of pretending the climb was easy.',
    'My strength is not the absence of fear; it is the decision to keep moving while afraid.',
    'I carry old grief and old courage in the same body, and both of them belong here.',
    'There is a steadiness in me that no one handed to me; I built it, one impossible day at a time.',
    'I am allowed to be soft and unbreakable at once, like water that quietly wears down stone.',
    'When I look back at everything I have already endured, I stop doubting whether I can endure what is coming.',
    'My strength is real whether or not anyone is there to witness it.',
    'The places where I scarred over are now the places that hold the most weight.',
    'I let myself feel the full size of what I have been through, because shrinking it would dishonor how hard I fought.',
    'My resilience is quiet and rarely announces itself, but it has never once abandoned me.',
    'I am learning that asking for help is not the opposite of strength but one of its truest forms.',
    'I trust the version of me who has carried me this far, even on the days I cannot see her clearly.',
    'I refuse to mistake exhaustion for weakness, because being worn down is the cost of having carried so much.',
    'Some days my only act of strength is to stay, and staying is enough.',
    'I have been remade by what tried to undo me, and I would not trade the depth it gave me.',
    'My strength does not ask me to be unbothered; it only asks me to keep choosing myself.',
    'I am not waiting to become strong someday, because I am already drawing on strength I earned.',
    'When everything in my life asked me to give up, something in me answered with one more day, and it is answering still.',
    'I let the strength forged in my hardest years soften into a gentleness I can finally offer myself.',
    'I stopped measuring my strength by how little I struggle and started measuring it by how often I begin again.',
    'Even on the days I feel like the smallest version of myself, the whole history of my surviving is still standing behind me.',
  ],
  joy: [
    'I find joy in the smallest of miracles.',
    'Happiness is my natural state of being.',
    'I am surrounded by love and laughter.',
    'Today is a beautiful day to be alive.',
    'My heart is open to the wonders of the world.',
    'I radiate light and positivity wherever I go.',
    'I choose to see the sunny side of every situation.',
    'I am the creator of my own happiness.',
    'Everything is working out for my highest good.',
    'I attract delightful experiences.',
    'My life is a celebration.',
    'I smile and the world smiles with me.',
    'I am filled with vibrant energy and excitement.',
    'I embrace joy in all its forms.',
    'I am grateful for the happiness I feel today.',
    'I allow myself to feel pure joy.',
    'I spread happiness wherever I go.',
    'I find reasons to laugh every day.',
    'I am lighthearted and free.',
    'I attract positive and happy people.',
    'I choose joy over worry.',
    'I am playful and carefree.',
    'I find happiness in giving to others.',
    'I am at peace and full of joy.',
    'I let go of anything that dims my light.',
    'I am a source of happiness.',
    'I welcome fun and laughter into my life.',
    'I feel joy deep in my soul.',
    'I am energized by the beauty around me.',
    "I am delighted by life's surprises.",
    'I am cheerful and optimistic.',
    'I attract wonderful moments.',
    'I am content with who I am.',
    'I find bliss in the present.',
    'I am full of life.',
    'I am happy for no reason at all.',
    'I embrace every moment with joy.',
    'I feel alive and excited.',
    'I am open to all the happiness the universe offers.',
    'I am blessed with a joyful spirit.',
    'I laugh freely and often.',
    'I am uplifted by the good in the world.',
    'I find wonder in the everyday.',
    'I am happy to be me.',
    'I am bursting with positive energy.',
    'I celebrate my own happiness.',
    'I am cheerful in the face of challenges.',
    'I choose to focus on what brings me joy.',
    'I am surrounded by beauty and happiness.',
    'I feel gratitude and joy every day.',
    'I am at home in my happiness.',
    'I am alive with joy.',
    'I embrace the magic of each day.',
    'I am naturally happy.',
    'I take pleasure in simple things.',
    'I feel joyful from the moment I wake up.',
    'I am glowing with happiness.',
    'I find delight in learning new things.',
    'I attract moments of pure happiness.',
    'I am lighthearted and joyful.',
    'I celebrate the gift of life.',
    'I feel happiness bubbling up inside me.',
    'I am grateful for every happy memory.',
    'I am surrounded by positivity.',
    'I let happiness flow through me.',
    'I am a happy person.',
    'I find joy in connection with others.',
    'I am nourished by laughter.',
    'I feel joyful and free.',
    'I embrace a life of happiness.',
    'I am delighted to be here.',
    'I am happy with my life.',
    'I find joy even in difficult times.',
    'I am filled with warmth and happiness.',
    'I attract joyful experiences.',
    'I am a magnet for happiness.',
    'I am optimistic about the future.',
    'I feel happiness in my heart.',
    'I am happy to give and receive love.',
    'I radiate joy to everyone I meet.',
    'I find bliss in being myself.',
    'I am overflowing with happiness.',
    'I am at peace with the joy I feel.',
    'I am excited about my life.',
    'I welcome happiness with open arms.',
    'I am a beacon of joy.',
    'I feel deeply happy.',
    'I am smiling from the inside out.',
    'I am grateful for the joy in my life.',
    'I feel lighthearted and carefree.',
    'I embrace life with enthusiasm.',
    'I am full of positive emotions.',
    'I cherish every joyful moment.',
    'I am happy to be alive.',
    'I let joy lead the way.',
    'I am blessed with happiness.',
    'I feel uplifted and inspired.',
    'I attract endless joy.',
    'I am vibrantly happy.',
    'I choose happiness every single day.',
    'I am living a joyful life.',
    'I am allowed to feel good even when nothing has been earned, fixed, or finished.',
    'I let joy in without first checking whether I deserve it.',
    'Delight is not a reward for suffering; it is mine to take the moment I notice it.',
    'I can be a serious person and still be silly, and both are true at once.',
    'When something small pleases me, I stay there a while instead of hurrying past it.',
    'For years I braced for the next hard thing; today I set the bracing down and let my shoulders drop.',
    'Choosing happiness does not mean pretending the heavy things are light; it means refusing to let them take everything.',
    'I give myself permission to laugh on a day that is also hard.',
    'My pleasure does not have to be useful to be allowed.',
    'I no longer believe I must suffer to prove I am taking my life seriously.',
    'I let myself want things that are simply fun, for no reason deeper than that they are.',
    'Play is not a waste of the time I have; it is part of why the time is worth having.',
    'I can hold grief and gladness in the same afternoon without choosing between them.',
    'I release the old superstition that if I relax, something terrible will catch me unguarded.',
    'I am not betraying anyone by being okay, or even good, right now.',
    'The lightness I feel is real, and it owes no one an apology.',
    'I let my body move toward what feels good, not only toward what looks responsible.',
    'I notice the warmth of an ordinary moment and I call it joy, because that is its name.',
    'I am allowed to love a life that is still unfinished and still imperfect.',
    'When happiness arrives quietly, I greet it instead of interrogating it.',
    'I do not have to shrink my excitement to seem grown.',
    'Savoring is a skill, and I am letting myself get slowly, clumsily better at it.',
    'I can rest in contentment without scanning the horizon for what might go wrong.',
    'My capacity for joy is not naive; it was hard-won, and I get to keep it.',
    'I let delight be a little embarrassing if that is the price of feeling it all the way through.',
    'Today I choose one small thing for no reason but that it will make me happy.',
    'Feeling good now does not spend the good that is still on its way.',
    'I am allowed to take up room with my laughter.',
  ],
  confidence: [
    'I trust myself to figure it out, even when I cannot yet see how.',
    'My doubt is not a stop sign; it is the feeling of standing at the edge of something I am about to do anyway.',
    'I have survived every moment I once swore would undo me, and that quiet record is evidence I can lean on.',
    'I let my voice take up the room it needs, instead of shrinking it to keep everyone else comfortable.',
    'Confidence is not the absence of fear in me; it is the willingness to move while my hands are still shaking.',
    'I am allowed to be a beginner without being a fraud.',
    'When I speak, I do not apologize for taking up air before I get to what I mean.',
    'I know more than I give myself credit for, and I am done pretending otherwise.',
    'I begin without waiting for a room full of people to nod.',
    'The voice that tells me I am not ready is rarely an honest witness to what I can actually do.',
    'I act on my own judgment, trusting that I can adjust course if I turn out to be wrong.',
    'I can be unsure and capable in the same breath, and most days I am quietly both.',
    'I let myself be seen trying, because hiding has never once made me stronger.',
    'My competence does not vanish the second someone raises an eyebrow at it.',
    'I can hold my flaws and my gifts in the same open hand without dropping either.',
    'I stop waiting to feel ready before I do the thing, because the doing is what makes the readiness.',
    'I trust the steady part of me that already knows the answer before my fear talks over it.',
    'I give my own opinion real weight, even in a room of louder, surer voices.',
    'When I get it wrong, I correct it without putting myself on trial for it.',
    'I let go of the need to convince people who decided long ago not to be convinced.',
    'There is a settled authority in me, and it has stopped waiting for permission to exist.',
    'I let my work stand on its own, and I resist the old reflex to undercut it the moment it lands.',
    'I am learning to stay in the room with my own success instead of explaining it away.',
    'I move as the person I am becoming, not as the smallest version of me I once believed was the truth.',
    'The nerves I feel before something hard are proof that it matters to me, not a prophecy that I will fail.',
    'I trust that my voice carries weight even on the days it comes out trembling.',
    'I am not behind in some race I never agreed to run.',
    'I would rather be seen as I genuinely am than be admired for a version of me I have to keep performing.',
  ],
  resilience: [
    'I am still here, and that is not nothing — surviving was its own quiet, unwitnessed act of courage.',
    'I let myself bend in the wind, because bending is not the same as breaking, and neither is the same as failing.',
    'What broke me did not get the last word; I am the one still holding the pen.',
    'I honor the version of me who made it through the nights I was not sure I would.',
    'Healing moves in circles, not lines, and I release the shame of returning to a wound I thought I had left behind.',
    'I am allowed to rest before I am fully healed — recovery is not a performance I owe to anyone watching.',
    'My scars are records of repair, not verdicts of weakness.',
    'Some days my only victory is rising at all, and I let that be a victory worth keeping.',
    'I am learning to trust the ground again, slowly, after it opened beneath me without warning.',
    'The fear still living in my body is not a defect; it is the sentinel that kept watch when no one else would.',
    'I do not have to be grateful for my pain in order to grow through it.',
    'I am tender and I am unbroken, and I no longer need to choose between the two.',
    'Beginning again does not erase the distance I had already crossed before everything came apart.',
    'I give myself permission to grieve what my resilience cost me, even while I keep moving forward.',
    'I am not the wreckage; I am the one walking out of it, one deliberate step at a time.',
    'What once felt unsurvivable is now behind me, and I am the living proof that it passed.',
    'I let small mercies — warm water, early light, one full breath — rebuild me without my forcing it.',
    'My strength was never the absence of falling apart; it is the gentleness with which I gather myself back together.',
    'I forgive the self who survived in the only ways she knew, with the only tools she had.',
    'I am allowed to outgrow the armor that once kept me alive but now only keeps me small.',
    'Starting over is not a sentence for what I lost; it is a door I finally get to choose.',
    'I trust that the places where I cracked are exactly where the light is finding its way in.',
    'The same heart that was wounded is the one still brave enough to want, to reach, to hope.',
    'I do not need to know how this ends in order to keep turning the page.',
    'I am rebuilding on ground I chose this time, and choosing it changes everything.',
    'Where I am soft, I am also unyielding — softness was never the opposite of strength.',
    'I release who I had to become to survive, and I make room for who I get to become now.',
    'I have outlived the worst predictions I ever made about myself, and I am still becoming.',
  ],
  growth: [
    'I am a work in progress, and the working is the point.',
    'I let myself be a beginner again, fumbling and curious, without apologizing for what I do not yet know.',
    'Today I trade the exhausting performance of having it together for the quieter dignity of figuring it out.',
    'I am not behind; I am exactly where the becoming requires me to be.',
    'I let my failures teach me what comfort never could.',
    'The messy middle is not a detour from my life; it is my life, unfolding in real time.',
    'I release the fantasy of a finished version of myself and turn toward the one who is actually here.',
    'I can hold disappointment and hope in the same two hands without choosing between them.',
    'I am learning to love the quiet seasons, when nothing shows on the surface and everything is moving underground.',
    'I give myself permission to do this badly long before I ever do it well.',
    'When I stumble, I am gathering information, not collecting evidence against myself.',
    'I am willing to outgrow the identities that once kept me safe but now keep me small.',
    'I trust that this discomfort is often the feeling of expanding, not the feeling of breaking.',
    'Progress no one claps for still counts, and I am the one who counts it.',
    'I loosen my grip on who I thought I would be by now, and stay tender toward who I am becoming.',
    'I am allowed to change my mind, to revise, to begin a paragraph of my life over again.',
    'Some days, growth simply means I did not abandon myself, and that is more than enough.',
    'I welcome the questions I cannot yet answer, trusting I will grow into their replies.',
    'I am not the person who started this, and I refuse to judge my middle by my beginning.',
    'The parts of me that feel unfinished are not flaws to hide but rooms still being built.',
    'I choose curiosity over contempt when I notice how far I still have to go.',
    "I honor the earlier version of me who endured enough to make today's growth possible.",
    'I let myself be seen mid-attempt, awkward and earnest, instead of hiding until I am polished enough to deserve it.',
    'I am gentle with the pace of my own unfolding, because no season ever arrived faster for being rushed.',
    'What looks like falling apart is sometimes the old shape loosening so a truer one can come through.',
    'I do not have to feel ready to begin; readiness is something I build only by beginning.',
    'Every quiet return to myself, after I have drifted, is its own act of growth.',
  ],
  'letting-go': [
    'I am allowed to grieve what I wanted as fiercely as what I actually had.',
    'I release my grip on the future I had already started furnishing in my mind.',
    'Some doors close softly and some slam, and either way I can stop standing in the doorway waiting to be let back through.',
    'Acceptance is not approval; I can stop fighting something without ever once agreeing it was fair.',
    'Today I let one heavy thing rest in my open palm instead of my clenched fist.',
    'I forgive myself for the years I spent trying to fix what was never mine to fix.',
    "I make room for the ache, because pretending it isn't there has never once made it leave.",
    'What is over is over, and I am gently turning my whole body toward what is still here.',
    'I no longer audition for the love of people who have already finished deciding about me.',
    'I let the apology I will never receive stop being the price of my peace.',
    'I can miss someone with my whole chest and still be certain I was right to walk away.',
    'Holding on tighter has never once kept anything that had already chosen to go.',
    'I keep the effort, which was always mine, and I release the outcome, which never was.',
    'I let the past be a place I visit, not a house I keep paying rent to live in.',
    'Grief is the shape love takes when it has nowhere left to go, and I let mine move through me instead of harden inside me.',
    'I stop rehearsing conversations with people who will never show up to have them.',
    'I am setting down the story where I was the only one who could have stopped this.',
    "Letting go does not mean it didn't matter; it means I have finally decided that I matter too.",
    'I allow the ending to simply be an ending, without forcing it to become a lesson before I am ready.',
    'I release my need to understand exactly why before I am allowed to begin feeling better.',
    'What I cannot change, I can at least stop carrying as though it were still my job to hold.',
    'I am loosening my hands one finger at a time, trusting that letting go is not the same as falling.',
    'I let people be exactly who they have shown me they are, and I quietly build my life around the truth.',
    'There is a steady, unglamorous strength in saying this is how it is now, and actually meaning it.',
    'I give myself permission to outgrow a grief I once swore would define me for the rest of my life.',
    'I am not behind; I am simply somewhere I never planned to be, and I am still on my way.',
    'I release the strange guilt of healing, of laughing again, of being okay before I believed I had earned it.',
    'I let the wave rise all the way up, knowing it has always, eventually, returned to the sea.',
  ],
  presence: [
    'I am here, in this breath, and this breath is enough to stand on.',
    'When my mind sprints toward tomorrow, I walk it gently back to my own two feet.',
    'I notice the weight of my body in the chair, the air against my skin, the small undeniable proof that I exist right now.',
    'I do not have to solve my whole life today; I only have to meet what is in front of me.',
    'My breath is always waiting for me, patient as a doorway back into now.',
    'I set down the rerun of what already happened, because it cannot be rewritten from where I stand.',
    'I give my full attention to one thing, and I let that small act be a quiet form of love.',
    'Even my restlessness is happening now, and I can be tender toward that too.',
    'I taste this food, I hear this sound, I feel this warmth, instead of hurrying past the only life I have.',
    'When worry arrives, I greet it without obeying it, and I return my eyes to the room.',
    'I stop bracing for a moment that has not come and let myself arrive in this one.',
    'This pause between tasks is not the gap in my life; it is my life.',
    'I name three things I can see, and the noise in my head loses its grip.',
    'I let difficult feelings stay in the room without needing to fix them or flee.',
    'I am not behind; I am simply here, and here is the only place anything has ever happened.',
    'I soften my shoulders, unclench my jaw, and remember that nothing is asking to be survived in this exact instant.',
    'I trade the urge to capture this moment for the deeper gift of being inside it.',
    'My attention is the most honest thing I own, and today I choose where to spend it.',
    'The past visits as memory and the future as imagination, but only now is solid enough to hold.',
    'I let the day move at the speed of my breathing rather than the speed of my fear.',
    'I forgive myself for drifting, and I begin again, as many times as it takes.',
    'Peace is not waiting somewhere ahead of me; it is here, underneath the noise, if I stop running long enough to feel it.',
    'I do not need this moment to be better before I am willing to be inside it.',
    'I stop waiting for my real life to start and notice, with something like relief, that it already has.',
    'Wherever my mind has wandered, I can come home in a single breath, and I am always welcome here.',
    'I hold what is in my hands right now as if it were the whole of the world, because for this moment it is.',
  ],
  purpose: [
    'I am allowed to live for something larger than my own comfort, and that pull toward meaning is not naive — it is the oldest, truest part of me speaking.',
    'My work matters not because the world has clapped for it, but because I put something honest of myself into it where no one was looking.',
    'I choose to spend my days on what I would still care about if no one were keeping score, and no one ever applauded.',
    'There is a specific shape to what I can offer that no one else can replicate, and somewhere the world is quietly shaped around its absence.',
    "I release the demand that my purpose be grand; tending one small corner of life with real attention is a whole life's work.",
    'On the days my sense of meaning goes silent, I trust that it is resting underground, gathering, not gone.',
    'I am willing to do the unglamorous work, the kind no one will photograph, because I know exactly who it carries.',
    'Living by my values costs me things, and I have decided to pay that price on purpose rather than lose it by accident.',
    'I do not have to find my whole purpose at once; I can follow it the way you follow a path at night, one honest step lit at a time.',
    'I refuse to hand the question of what my life is for to anyone who profits from keeping me distracted from it.',
    'When my contribution feels invisible, I remember that the roots that hold everything up are the ones no one ever sees.',
    'I am the only person who will ever stand exactly where I stand, see what I see, and have to choose what to do about it.',
    'I let my grief over what is broken point me, like a compass needle, toward where I am meant to give.',
    'I would rather build something slow and true than be carried fast toward something hollow.',
    'Purpose does not erase my exhaustion, but it gives my exhaustion a direction worth spending it on.',
    'I let my ordinary acts — the meal made, the message sent, the patience held when it cost me — count as the real work, because they are.',
    'I choose to be useful to the people in front of me before I worry about being useful to the world.',
    'My life is allowed to be a quiet, lifelong answer to a question that was only ever asked of me.',
    'I stop waiting to feel ready and let my values walk a few steps ahead of my confidence.',
    'I am willing to be changed by what I love, even when that change asks more of me than I planned to give.',
    'The difference I make may never be measured by anyone, and I have decided to make it anyway.',
    'I honor the seasons of my purpose that look, from the outside, like nothing at all is happening — and are everything.',
    'I let myself want a meaningful life out loud, plainly, without apologizing for taking my own one life seriously.',
    'When I am tempted to drift, I return to the simple, sobering truth of what I do not want to have wasted.',
    'I am building a life my future self could look back on and recognize, without flinching, as honestly mine.',
    'I give my attention to what is alive and worthy of it, and I let the rest fall away without guilt or apology.',
    'My purpose is not a place I finally arrive at but a way of being present that I get to choose again today.',
    'I trust that showing up with integrity, again and again when no one would notice if I stopped, is itself the contribution this world is starving for.',
  ],
  boundaries: [
    'No.',
    'Saying no is a complete sentence; I no longer owe anyone the essay that softens it.',
    'I am allowed to protect my peace, even from people who never meant to disturb it.',
    'The guilt that arrives after I set a limit is not evidence of wrongdoing; it is an old habit feeling itself lose its grip.',
    'When my body tightens around a request, I let that tension be information instead of overriding it to keep someone comfortable.',
    'My time is not a public resource that anyone may draw from simply because they thought to ask.',
    'I can love someone with my whole heart and still decline to be the place where they unload everything they refuse to carry.',
    'When I choose myself, I am not abandoning anyone; I am finally counting myself among the people I take care of.',
    'I release the belief that being easy to be around requires me to slowly disappear.',
    'A boundary is not a wall I raise against you; it is the doorway through which I can keep meeting you without resentment.',
    'I am learning that the people most angered by my limits are often the ones who benefited most from my having none.',
    'I do not have to earn rest by first running myself into the ground.',
    'I let my no arrive on time, before the slow leak of overcommitment becomes a flood of regret.',
    'My discomfort with disappointing someone is real, and it is still smaller than the cost of betraying myself.',
    'I decide how much of me is available, and to whom, and when, and I do not have to justify the math.',
    'Quietly, without announcement or apology, I am taking my energy back from the rooms it was never welcome in.',
    "I can hold tenderness for someone's pain without taking responsibility for fixing it.",
    'Some relationships asked me to shrink for so long that standing at my full height now feels like rebellion, and I welcome it.',
    'I am not too sensitive; I have simply spent years ignoring signals I am finally willing to honor.',
    'When someone tests the line I have drawn, I do not need to defend it, only to keep it.',
    "I am allowed to leave the conversation, the room, the dynamic that drains me, without a flawless exit or anyone's permission.",
    'I can let people be disappointed in me and still know, all the way down, that I am good.',
    'The version of me who said yes to everything was trying to keep me safe, and I thank her even as I set her down.',
    'I do not have to be endlessly available in order to be loved.',
    'I am becoming someone who does not collapse every time another person needs her to.',
    'My silence is not consent, and my kindness is not an open invitation.',
    'I trust that the right people will stay even after I stop overextending to keep them.',
    'I am allowed to outgrow what once required my smallness.',
  ],
  forgiveness: [
    'I am allowed to set down what I have been carrying, even if I picked it up so long ago that the weight feels like a part of me.',
    'I forgive the version of me who was doing the best they could with what they understood, in a moment they did not yet know how to survive.',
    'I release the grip of resentment, not because the wound was small, but because I no longer want to spend my one life living inside it.',
    'The worst thing I ever did is not the whole truth of who I am.',
    'I hold both at once: I was wronged, and I still deserve to be free.',
    'I stop rehearsing the apology that is never going to come.',
    'I let the old wound breathe instead of pressing on it to make sure it still hurts.',
    'Carrying this anger has cost me far more than it ever cost the person who caused it, and I am done paying.',
    'I forgive myself for not knowing then what only time and pain could ever teach me.',
    'I do not have to forget what happened to soften the way I hold it.',
    'I release the people who could not love me the way I needed, and I release the wish to go back and make them.',
    'The shame I have been hoarding was never proof of how bad I am, only of how much I cared.',
    'I am no longer both the prosecutor and the accused in a trial that refuses to end.',
    'I let go of the quiet belief that staying angry is what keeps me safe.',
    'I make peace with the choices I cannot take back, and I let them teach me instead of haunt me.',
    'I am gentle with the part of me that still flinches, and I do not rush it to heal.',
    'I extend to my younger self the same patience I would offer a frightened, struggling friend.',
    'Resentment kept me chained to what hurt me; forgiveness hands me back my own life.',
    'I free myself from the impossible labor of perfecting a past that is already finished.',
    'I meet my own failures with curiosity instead of contempt.',
    'I can name the damage honestly and still refuse to let it write my tomorrow.',
    'I grieve what I lost and walk forward anyway, no longer dragging it behind me.',
    'I loosen my grip on the story where I am the villain of my own life.',
    'Forgiving you does not mean what you did was okay; it means I am taking my peace back from you.',
    'Peace is not the disappearance of the memory, but my quiet refusal to let it own me.',
    'I am someone who has been hurt and someone who is still whole, and both can be true of me.',
  ],
  hope: [
    'I do not have to feel hopeful to act with hope; today, the smallest step forward counts as faith.',
    'The future is unwritten, and that means there is still room in it for me.',
    "I hold my hope honestly, not by pretending the dark isn't dark, but by trusting the dark is not the whole story.",
    'I let myself want things again, even knowing that wanting is how the heart stays open to being hurt.',
    'Light has come back to me before, after nights I was sure would never end, and I let that memory speak for the nights ahead.',
    'I am allowed to grieve what is hard and still believe something gentler is on its way.',
    'Tomorrow does not need me to predict it; it only asks me to stay long enough to meet it.',
    'I plant things whose blooming I may never get to see, and I call that an act of love.',
    'Hope, for me, is not a feeling that arrives but a direction I keep turning toward.',
    'I release the demand to know how it all works out before I am willing to keep going.',
    'Even here, in the middle of the unfinished, I am allowed to imagine a life that fits me better.',
    'Healing rarely announces itself; more often it is already happening quietly while I doubt it.',
    'When despair insists that nothing will change, I remember that despair has been wrong before.',
    'I do not need certainty to keep my heart open; I only need a little willingness.',
    'What feels permanent right now is, more often than I admit, a season I am passing through.',
    'I make room for the possibility that the best thing in my life has not happened yet.',
    'Faith, for me, is watering the ground on the days I cannot feel the roots.',
    'I forgive myself for the times hope felt impossible, and I welcome it back without shame.',
    'The same uncertainty that frightens me is the only place where everything good still has a chance to begin.',
    'I carry a quiet expectation that the kindness I give will find its way back around.',
    'I let tomorrow stay unknown, and I let the unknown be a door rather than a threat.',
    'I am still here, and as long as that is true, the possibility of change is true with me.',
    'I do not have to carry the whole future today; I only have to keep the next door from closing.',
    'Despair feels like the truth because it is loud, but I have learned that loud and true are not the same thing.',
  ],
}

const fallbackAffirmations = [
  'I am growing every day.',
  'I choose positivity.',
  'I am capable.',
  'My life is filled with light.',
]

export function getAffirmations(categoryId: string): string[] {
  return affirmationTemplates[categoryId] || fallbackAffirmations
}

/** Every affirmation across all categories, deduped, in a stable order. */
export const allAffirmations: string[] = Array.from(
  new Set(Object.values(affirmationTemplates).flat()),
)

/** A small deterministic hash for a string — used to seed daily selection. */
function hashString(value: string): number {
  let hash = 0
  for (let i = 0; i < value.length; i++) {
    hash = (hash << 5) - hash + value.charCodeAt(i)
    hash |= 0
  }
  return Math.abs(hash)
}

/** A YYYY-MM-DD key for a date in the user's local timezone. */
export function getDayKey(date: Date = new Date()): string {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/**
 * The affirmation of the day. Deterministic for the whole calendar day, so it
 * never changes on refresh and is the same every time you open the app today.
 */
export function getDailyAffirmation(date: Date = new Date()): string {
  if (allAffirmations.length === 0) return fallbackAffirmations[0]
  const index = hashString(getDayKey(date)) % allAffirmations.length
  return allAffirmations[index]
}
