import type { RawMoneyData } from './money-types'

export function createSeedMoneyData(now = new Date()): RawMoneyData {
  const asOf = now.toISOString()
  const year = now.getUTCFullYear()
  const month = String(now.getUTCMonth() + 1).padStart(2, '0')

  return {
    accounts: [
      {
        id: 'seed-checking',
        source: 'seed',
        institutionName: 'Moldable Seed Bank',
        name: 'Checking',
        type: 'cash',
        currentBalance: 12842,
        isoCurrencyCode: 'USD',
        asOf,
      },
      {
        id: 'seed-investments',
        source: 'seed',
        institutionName: 'Moldable Brokerage',
        name: 'Investments',
        type: 'investment',
        currentBalance: 111921,
        isoCurrencyCode: 'USD',
        asOf,
      },
      {
        id: 'seed-credit-card',
        source: 'seed',
        institutionName: 'Moldable Card',
        name: 'Credit Card',
        type: 'credit',
        currentBalance: -2712,
        isoCurrencyCode: 'USD',
        asOf,
      },
      {
        id: 'seed-student-loan',
        source: 'seed',
        institutionName: 'Moldable Loans',
        name: 'Student Loan',
        type: 'loan',
        currentBalance: -14800,
        isoCurrencyCode: 'USD',
        asOf,
      },
    ],
    transactions: [
      {
        id: 'seed-income-payroll',
        source: 'seed',
        accountId: 'seed-checking',
        name: 'Payroll',
        merchantName: 'Acme Payroll',
        amount: 9200,
        direction: 'income',
        category: ['Income', 'Payroll'],
        date: `${year}-${month}-01`,
        isoCurrencyCode: 'USD',
        recurring: true,
      },
      {
        id: 'seed-rent',
        source: 'seed',
        accountId: 'seed-checking',
        name: 'Rent',
        merchantName: 'Home',
        amount: 2800,
        direction: 'expense',
        category: ['Housing', 'Rent'],
        date: `${year}-${month}-03`,
        isoCurrencyCode: 'USD',
        recurring: true,
      },
      {
        id: 'seed-groceries',
        source: 'seed',
        accountId: 'seed-credit-card',
        name: 'Groceries',
        merchantName: 'Market',
        amount: 842,
        direction: 'expense',
        category: ['Food', 'Groceries'],
        date: `${year}-${month}-06`,
        isoCurrencyCode: 'USD',
        recurring: false,
      },
      {
        id: 'seed-netflix',
        source: 'seed',
        accountId: 'seed-credit-card',
        name: 'Netflix',
        merchantName: 'Netflix',
        amount: 22,
        direction: 'expense',
        category: ['Entertainment', 'Subscription'],
        date: `${year}-${month}-08`,
        isoCurrencyCode: 'USD',
        recurring: true,
      },
      {
        id: 'seed-amazon',
        source: 'seed',
        accountId: 'seed-credit-card',
        name: 'Amazon Prime',
        merchantName: 'Amazon',
        amount: 15,
        direction: 'expense',
        category: ['Shopping', 'Subscription'],
        date: `${year}-${month}-09`,
        isoCurrencyCode: 'USD',
        recurring: true,
      },
    ],
  }
}
