// The style library — studio-grade. Each template lives in its own module under
// ./decks/<id>.ts and ships a comprehensive, fully-filled-in sample deck (its own
// "presentation to tweak"): bespoke decoration, generated imagery, charts and
// diagrams. All slides compose the shared component vocabulary in ./types.ts.
//
// GENERATED by scripts/build-catalog.mjs — do not hand-edit the lists below.
// To add a template: drop a module in ./decks/<id>.ts exporting a `Template`,
// add its id to ORDER in the script, then run `node scripts/build-catalog.mjs`.
import { allHands } from './decks/all-hands'
import { annualReport } from './decks/annual-report'
import { boldFounder } from './decks/bold-founder'
import { brandGuidelines } from './decks/brand-guidelines'
import { campaignBrief } from './decks/campaign-brief'
import { caseStudy } from './decks/case-study'
import { charcoal } from './decks/charcoal'
import { classroom } from './decks/classroom'
import { cleanMinimal } from './decks/clean-minimal'
import { companyOverview } from './decks/company-overview'
import { competitiveBattlecard } from './decks/competitive-battlecard'
import { consulting } from './decks/consulting'
import { courseCurriculum } from './decks/course-curriculum'
import { darkTech } from './decks/dark-tech'
import { dataDashboard } from './decks/data-dashboard'
import { editorial } from './decks/editorial'
import { executiveReview } from './decks/executive-review'
import { financePro } from './decks/finance-pro'
import { flatIllustration } from './decks/flat-illustration'
import { gtmStrategy } from './decks/gtm-strategy'
import { investorUpdate } from './decks/investor-update'
import { isometric } from './decks/isometric'
import { literary } from './decks/literary'
import { marketAnalysis } from './decks/market-analysis'
import { moodboard } from './decks/moodboard'
import { nonprofitAppeal } from './decks/nonprofit-appeal'
import { okrReview } from './decks/okr-review'
import { onboarding } from './decks/onboarding'
import { pastelCreative } from './decks/pastel-creative'
import { peopleOps } from './decks/people-ops'
import { portfolio } from './decks/portfolio'
import { pricingProposal } from './decks/pricing-proposal'
import { productBrief } from './decks/product-brief'
import { projectKickoff } from './decks/project-kickoff'
import { projectTimeline } from './decks/project-timeline'
import { research } from './decks/research'
import { risograph } from './decks/risograph'
import { salesDeck } from './decks/sales-deck'
import { seedPitch } from './decks/seed-pitch'
import { seminar } from './decks/seminar'
import { sprintReview } from './decks/sprint-review'
import { statusReport } from './decks/status-report'
import { strategyFramework } from './decks/strategy-framework'
import { teamRetrospective } from './decks/team-retrospective'
import { webinar } from './decks/webinar'
import { weeklyUpdate } from './decks/weekly-update'
import { workshop } from './decks/workshop'
import type { Template } from './types'

export const TEMPLATES: Template[] = [
  cleanMinimal,
  allHands,
  companyOverview,
  weeklyUpdate,
  teamRetrospective,
  editorial,
  pastelCreative,
  brandGuidelines,
  portfolio,
  moodboard,
  risograph,
  charcoal,
  classroom,
  seminar,
  research,
  literary,
  courseCurriculum,
  workshop,
  financePro,
  executiveReview,
  annualReport,
  dataDashboard,
  okrReview,
  productBrief,
  projectTimeline,
  projectKickoff,
  sprintReview,
  statusReport,
  boldFounder,
  seedPitch,
  investorUpdate,
  nonprofitAppeal,
  darkTech,
  salesDeck,
  competitiveBattlecard,
  caseStudy,
  pricingProposal,
  flatIllustration,
  isometric,
  gtmStrategy,
  campaignBrief,
  marketAnalysis,
  webinar,
  consulting,
  strategyFramework,
  peopleOps,
  onboarding,
]
