#!/usr/bin/env node
// Regenerate src/shared/templates/catalog.ts by scanning decks/*.ts.
// Collision-free wiring: agents drop a module in decks/, this re-derives the
// import list + TEMPLATES array. Order = ROSTER preference, then any extras.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const decksDir = path.resolve(here, '../src/shared/templates/decks')
const catalogPath = path.resolve(here, '../src/shared/templates/catalog.ts')

// Preferred display order (ids). Unlisted modules are appended alphabetically.
const ORDER = [
  // Company
  'clean-minimal',
  'all-hands',
  'company-overview',
  'weekly-update',
  'team-retrospective',
  // Creative
  'editorial',
  'pastel-creative',
  'brand-guidelines',
  'portfolio',
  'moodboard',
  'risograph',
  'charcoal',
  // Education
  'classroom',
  'seminar',
  'research',
  'literary',
  'course-curriculum',
  'workshop',
  // Reporting
  'finance-pro',
  'executive-review',
  'annual-report',
  'data-dashboard',
  'okr-review',
  // Project Management
  'product-brief',
  'project-timeline',
  'project-kickoff',
  'sprint-review',
  'status-report',
  // Fundraising
  'bold-founder',
  'seed-pitch',
  'investor-update',
  'nonprofit-appeal',
  // Sales
  'dark-tech',
  'sales-deck',
  'competitive-battlecard',
  'case-study',
  'pricing-proposal',
  'flat-illustration',
  'isometric',
  'open-house',
  // Marketing
  'gtm-strategy',
  'campaign-brief',
  'market-analysis',
  'webinar',
  // Consulting
  'consulting',
  'strategy-framework',
  // People
  'people-ops',
  'onboarding',
  'working-session',
  'security-training',
]

const files = fs.readdirSync(decksDir).filter((f) => f.endsWith('.ts'))
const mods = []
for (const f of files) {
  const src = fs.readFileSync(path.join(decksDir, f), 'utf8')
  const exp = src.match(/export const (\w+)\s*:\s*Template\s*=/)
  const idm = src.match(/\bid:\s*'([^']+)'/)
  if (!exp || !idm) {
    console.warn(`! skipped ${f} (no exported Template / id)`)
    continue
  }
  mods.push({ file: f.replace(/\.ts$/, ''), exportName: exp[1], id: idm[1] })
}

mods.sort((a, b) => {
  const ia = ORDER.indexOf(a.id),
    ib = ORDER.indexOf(b.id)
  if (ia !== -1 && ib !== -1) return ia - ib
  if (ia !== -1) return -1
  if (ib !== -1) return 1
  return a.id.localeCompare(b.id)
})

const imports = mods
  .map((m) => `import { ${m.exportName} } from './decks/${m.file}'`)
  .join('\n')
const arr = mods.map((m) => `  ${m.exportName},`).join('\n')

const out = `// The style library — studio-grade. Each template lives in its own module under
// ./decks/<id>.ts and ships a comprehensive, fully-filled-in sample deck (its own
// "presentation to tweak"): bespoke decoration, generated imagery, charts and
// diagrams. All slides compose the shared component vocabulary in ./types.ts.
//
// GENERATED by scripts/build-catalog.mjs — do not hand-edit the lists below.
// To add a template: drop a module in ./decks/<id>.ts exporting a \`Template\`,
// add its id to ORDER in the script, then run \`node scripts/build-catalog.mjs\`.

import type { Template } from './types'

${imports}

export const TEMPLATES: Template[] = [
${arr}
]
`

fs.writeFileSync(catalogPath, out)
console.log(`wired ${mods.length} templates -> catalog.ts`)
for (const m of mods) console.log(`  ${m.id.padEnd(24)} ${m.exportName}`)
